### ISSUE TITLE
Do not show workspace to unauthorized people

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-correction#103]

**Comment by 12oprs** [comment]
как  это должно выглядеть без страницы login in/sign in ? :
 - все пользователи по умолчанию имеют право просматривать воркспейсы
 - никто ниче не сможет посмотреть (но это неудобно)
 - сделать авторизацию, но оставить  в нерабочем состоянии
 - сделать запуск в параметром для включения/отключения процесса авторизации (например дописать в Makefile команду)
 - другой вариант
 
может я понял задачу не так как на самом деле, задай направление плз)

**Comment by acidmaksim** [comment]
@12oprs нужно сделать так, чтобы человек не привязанный к воркспейсу не смог зайти в него и смотреть, что там происходит. Соответственно для этого нужно сначала сделать регистрацию пользователей и добавить им роли. @kacetal поправь меня, если не прав

**Comment by 12oprs** [comment]
роли в #104 , регистрация в #96, значит с этим стоит подождать я так понимаю.

**Comment by kacetal** [comment]
Да всё верно, но первым шагом нужно сделать регистрацию.

**Comment by 12oprs** [comment]
регистрацию ведь сделают в 96 вместе со страничкой ?

**Comment by acidmaksim** [comment]
Задача свободна

**Comment by nekedio** [comment]
Попробую сделать

**Comment by anasasiia** [comment]
Возьму задачу

**Comment by fey** [comment]
@anasasiia сейчас эта задачка в работе, вот пр https://github.com/Hexlet/hexlet-correction/pull/150
Я предлагаю взять вам вот эту задачку - https://github.com/Hexlet/hexlet-correction/issues/139
поскольку сервис мы делаем для не-программистов, нам важно дать возможность скопировать готовый код, который нужно будет вставить к себе.

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-correction/pull/150
