### ISSUE TITLE
Add different roles with rights

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-correction#104]
Add different roles with rights:
- [ ] User - can view the workspace, but cannot edit or comment;
- [ ] Corrector - Corrector - can edit workspace;
- [ ] Admin -  can edit, delete, add workspace. Only the admin can see the workspace settings

**Comment by 12oprs** [comment]
Назначь мне плз, когда сделают регистрацию.

**Comment by 12oprs** [comment]
Привет! Отдай мне задачу, похоже пришло время её решить.

**Comment by acidmaksim** [comment]
@12oprs бери, он открыта

**Comment by anasasiia** [comment]
Задача еще актуальна?

**Comment by fey** [comment]
@anasasiia да, задача актуальная. Но перед этим нужно сперва посмотреть код. 
Пока нас роли не сильно интересуют, наша задача сделать просто рабочий сервис, чтобы можно было принимать опечатки.
Например можно глянуть эту задачку - https://github.com/Hexlet/hexlet-correction/issues/142

**Comment by fey** [comment]
Пока не актуально. Пока закрою, может быть и не будем роли делать.
