### ISSUE TITLE
Adds a link to the site

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-correction#107]
Add a link to the site on the workspace card
![image](https://user-images.githubusercontent.com/77053797/186100433-2bc54617-0019-4d2e-927f-093e5a29704b.png)

**Comment by Oleg995** [comment]
Давай я возьму

**Comment by Oleg995** [comment]
@acidmaksim добрый вечер, хотелось бы узнать следующее:
1. Какой должен быть текст у ссылки?
2. Куда должна вести ссылка?

**Comment by acidmaksim** [comment]
@Oleg995 Привет! Где написано URL - это должна быть ссылка на сайт из рабочего пространства. Соответсвенно она должна вести на сайт

**Comment by Oleg995** [comment]
@acidmaksim Добрый вечер. Я не понимаю какую ссылку выводить, так как ссылок в воркспейсе много
![image](https://user-images.githubusercontent.com/97472218/188330312-0731a0e2-db91-4fe6-a76e-cb9f0dfc270e.png)
их может быть 100, если речь о них, то не понятно по какому критерию выбирать?

**Comment by acidmaksim** [comment]
Есть воркспейс, он привязан к какому то сайту, например рогаикопыт.ру, соответсвенно ссылка этого сайта и должна быть на этом месте

**Comment by Oleg995** [comment]
Отложу задачу на пару недель

**Comment by devbulygin** [comment]
Возьму задачу!

**Comment by acidmaksim** [comment]
@devbulygin привет, задача понятна или нужна помощь?
