### ISSUE TITLE
Add a user page

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-correction#108]
Add a user page where he can add his name, mail, change the password and see all the workspaces in which he works

**Comment by wtffka** [comment]
я возьму

**Comment by acidmaksim** [comment]
@wtffka Как успехи с задачей?

**Comment by nikisysoev** [comment]
@acidmaksim Присоединяюсь

**Comment by acidmaksim** [comment]
@kacetal привет, сделай ревью, пожалуйста

**Comment by kacetal** [comment]
На выходных гляну
