### ISSUE TITLE
Make landing

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-correction#111]
Example: 
https://sicp.hexlet.io/ru
https://ru.hexlet.io/

**Comment by ElisabethFox** [comment]
Беру в работу

**Comment by ssssank** [comment]
@ElisabethFox как успехи?

**Comment by fey** [comment]
актуально.

**Comment by KindProgrammer** [comment]
Добрый день! Хотелось бы поподробнее узнать о задаче: лендинг надо самостоятельно разработать или сверстать по макету? Есть ли какие-нибудь наработки?

**Comment by HelenOne** [comment]
@KindProgrammer, добрый день! Макета нет, нужно самостоятельно разработать

**Comment by fey** [comment]
А лендинг то нам сделали же https://fixit.hexlet.io/ 
![image](https://github.com/user-attachments/assets/e775c2d8-9f76-47aa-8d89-04f98e49cce1)
