### ISSUE TITLE
Add frontend in widget

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-correction#117]

**Comment by MilaNick** [comment]
Беру)

**Comment by acidmaksim** [comment]
#78 дубль

**Comment by MilaNick** [comment]
Возможно дубль, но не я его создавала, и 117 дубль, потому что появился 118 (тут я создатель) и туда перешла вся задача, которая на данный момент не закончена, требуется исправить ошибки. Задача свободна.
