### ISSUE TITLE
make run-dev command not runs.

### ISSUE THREAD

**Issue by Daukaevt** [Hexlet/hexlet-correction#122]
Command 'make run-dev' from README.md
gives an error:
java -jar -Dspring.profiles.active=dev ./target/hexlet-typo-reporter-*.jar
Error: Unable to access jarfile ./target/hexlet-typo-reporter-*.jar
make: *** [Makefile:25: run-dev] Ошибка 1

**Comment by RedGradient** [comment]
Hi!
The `make run-dev` command makes two assumptions:
1. Project already builded
2. The database is started (although from the description you might think that the database will be started automatically)

So, to start the project you should:
```bash
./mvnw package # build the project
make run-dev-docker-db # run db in docker and start the application
```

**Comment by prozet-x** [comment]
@fey а эта ищью точно актуальна? Вроде, эта команда норм запускается.

**Comment by fey** [comment]
Ok, давайте закрывать если не актуально)
