### ISSUE TITLE
Нужно заменить ручной маппинг сущностей в DTO на библиотеку mapstruct

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-correction#125]
### Problem description

 -

### Proposed solution

Есть класс например такой, в пакете с конвертерами надо заменить ручной маппинг на автоматический с помощью библиотеки mapstruct, добавить ее в зависимости и правильно настроить взаимодействие с библиотекой Lombok. Через препроцессор аннотаций.

```
@Override
    public InfoAccount convert(final Account source) {
        return new InfoAccount(
            source.getEmail(),
            source.getUsername(),
            source.getFirstName(),
            source.getLastName()
        );
    }
```

**Comment by anasasiia** [comment]
Возьму задачу
