### ISSUE TITLE
Удалить старую ManyToOne связь на Workspace из Account

### ISSUE THREAD

**Issue by kacetal** [Hexlet/hexlet-correction#130]
### Problem description

Удалить старую ManyToOne связь на Workspace из Account, Так как теперь у нас есть ManyToMany связь с множеством Workspaces через промежуточную таблицу. Изменения затронут всё, от базы данных с созданием миграции на удаление колонки и до фронта  где нужно будет изменить страницу акаунта.

### Proposed solution

Удалить старую ManyToOne связь на воркспейс из Account

**Comment by asb1301** [comment]
Возьму
