### ISSUE TITLE
Bug: 500 if try to delete workspace

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#135]
### Summary

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Mar 24 15:51:54 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).

https://hexlet-correction.herokuapp.com/workspace/asdfas
Ошибка при попытке удалить вокрспейс

### Reproduction steps

```bash
1. Залогинился feycot@gmail.com
2. Ввел рандомные данные для воркспейса
3. Нажимаю удалить
4. Получаю сообщение об ошибке
```

### Expected result

Страница с ошибкой

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Mar 24 15:51:54 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).

https://hexlet-correction.herokuapp.com/workspace/asdfas
Ошибка при попытке удалить вокрспейс

### Actual result

При нажатии на кнопку удаления открывается подтверждение о желании удалить, если подтвердить, то воркспейс будет удален.

### Browsers

Chrome

### OS

Linux

**Comment by agsamkin** [comment]
Взял задачу

**Comment by agsamkin** [comment]
Привет! Проблема была исправлена и PR принят - https://github.com/Hexlet/hexlet-correction/pull/138
Задачу закрыть можно наверное или есть еще прорблемы с удалением?

**Comment by fey** [comment]
угу, работает
