### ISSUE TITLE
Add form to copy widget code

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#139]
### Problem description

Сейчас пользователю предлагается использовать curl для выполнения запросов. 

Для обычного пользователя это сложно.
![image](https://user-images.githubusercontent.com/697178/230710518-ca12d68f-0421-4aad-8088-8308eca0a48d.png)

### Proposed solution

Добавить на страницу форму для копирования виджета
Там готовый код, который нужно скопировать и себе вставить на страницу.

**Comment by fey** [comment]
У нас есть html с примером.
https://github.com/Hexlet/hexlet-correction/blob/main/src/widget/index.html#L222-L223

Там мы видим, что в функцию передается токен и ID воркспейса. Могут передаваться и другие настройки (их пока нет). 
Но нужно, чтобы сперва работало текущее решение.

**Comment by xushaha** [comment]
Возьму задачу

**Comment by xushaha** [comment]
Задача в процессе, не брошена)

**Comment by ssssank** [comment]
@fey и здесь уже вполне рабочий вариант получился

**Comment by fey** [comment]
Ага, тут работает. 
https://github.com/Hexlet/hexlet-correction/pull/158
https://github.com/Hexlet/hexlet-correction/pull/164
