### ISSUE TITLE
fix path to send typos

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#140]
### Problem description

Сейчас эндпоинт, куда отправляются опечатки не тот, что нужно. 
`http://localhost:8080/api/workspaces/typos`

### Proposed solution

Урл должен быть вида `http://localhost:8080/api/workspaces/:id/typos`
Т.е. в урле должно быть разделение по воркспейсам.

**Comment by anasasiia** [comment]
Возьму задачу
