### ISSUE TITLE
Create form for type reporter widget

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#141]
### Problem description

нет модалки для отправки кода

### Proposed solution

![image](https://user-images.githubusercontent.com/697178/230714225-e59b06d5-3c59-462a-8f5d-6d785542204d.png)

Логика какая - пользователь выделяет текст, нажимает ctrl + enter и видит модалку.

В ней часть полей уже заполнены

* урл откуда отправка - ридонли
* выделенный текст
* Текст до выделения (скрытый инпут)
* текст после выделения (скрытй инпут)
* контакты отправителя
* коммент

Отправка выполняется на API тайпрепортера например на `https://hexlet-correction.herokuapp.com/api/workspaces/typos`

Изначально модалки нет в коде сайта, поэтому подключение модалки должно выполнятсья вызовом главной функции.

Для вдохновения
https://codepen.io/collection/KpRQkw

**Comment by fey** [comment]
Тут накидал демо, но успел сломать - https://gist.github.com/fey/6bf17761ce8177e46f9498c7a84ddba7#file-index-html

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-correction/issues/78

**Comment by fey** [comment]
Продолжаем работу. комментарии здесь - https://github.com/Hexlet/hexlet-correction/pull/149#issuecomment-1528055111

**Comment by ssssank** [comment]
И вот здесь продолжалась работа: #151 
@dzencot опиши, пожалуйста, что ещё осталось доделать и отрефакторить

**Comment by ssssank** [comment]
Нужно отрефакторить согласно тому, чему мы учим. Для студентов, прошедших 3-й проект. Код должен соответствовать MVC: в рендерах не должно быть изменение стейта, а в контроллерах вызовов рендера.

**Comment by zapupenec** [comment]
Попробую

**Comment by sgmdlt** [comment]
@fey
