### ISSUE TITLE
Fix cors error 

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#142]
### Problem description

По задаче - https://github.com/Hexlet/hexlet-correction/issues/141
Выяснилось, что нельзя отравлять из скрипта со страницы запрос из-за CORS

Сервисы типа allorigins тоже не помогают, тк не позволяют прокидывать хедер заголовка.

### Proposed solution

В настройки воркспейса добавить разрешение, откуда можно слать запросы.

Можно просто форму,куда можно урл закинуть.

**Comment by Malcom1986** [comment]
Забрал задачу
