### ISSUE TITLE
Показывать форму логина/регистрации на странице воркспейсов для гостей.

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#152]
### Problem description

Когда пользователь переходит с лендинга в сервис по кнопке "перейти в сервис", то он видит пустую страницу. А регистрация/логин находятся справа сверху. Непонятно, куда двигаться.

### Proposed solution

Не показывать страницу с воркспейсом гостям. Вместо этого требовать аутентификацию. После аутентификации можно показывать страницу с воркспейсами

**Comment by fey** [comment]
@anasasiia предлагаю вам взять эту задачку.

**Comment by anasasiia** [comment]
Ура, спасибо! Вот эту я точно возьму)
