### ISSUE TITLE
Bug: Ошибка 404 после добавления нового юзера в пространство

### ISSUE THREAD

**Issue by RedGradient** [Hexlet/hexlet-correction#162]
### Summary

После добавления нового пользователя в пространство возникает ошибка 404 из-за некорректного редиректа.

### Reproduction steps

```bash
(Зарегистрированных пользователей должно быть больше одного)
1. Создать пространство
2. Перейти в раздел Users/Пользователи
3. Добавить нового пользователя в пространство
Произойдет перенаправление на страницу с ошибкой 404.
```

### Expected result

Добавление пользователя должно завершиться простым обновлением страницы Users/Пользователи, чтобы показать обновленный список пользователей в пространстве.

### Actual result

Сейчас при добавлении пользователя в пространство происходит перенаправление на страницу ошибки Not Found 404.

**Comment by RedGradient** [comment]
#163

**Comment by ssssank** [comment]
@fey закрой, пожалуйста, проблема решена
