### ISSUE TITLE
bug: нельзя отредактировать url вокрспейса

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#165]
Форма редактирования воркспейса не дает поменять урл
![image](https://github.com/Hexlet/hexlet-correction/assets/697178/70b0ec7e-4ff6-4f33-ba3f-a35f341c0730)

**Comment by AlekseyNechunaev** [comment]
Привет, возьму

**Comment by AlekseyNechunaev** [comment]
@fey Отдал PR https://github.com/Hexlet/hexlet-correction/pull/184
