### ISSUE TITLE
ограничить длину пароля

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#166]
### Problem description

При валидации пароля (регистрации) просит длину пароля `size must be between 8 and 2147483647`,

### Proposed solution

 такой длинный пароль кажется не нужен и лучше ограничить до 20

**Comment by xushaha** [comment]
Беру задачу

**Comment by fey** [comment]
Еще проверьте, пожалуйста, что сообщение о валидации будет нормально отображаться.
Например там будет подсказка вида "допустымые символы такие-то, длина пароля минимум столько-то и максимум столько то". Т.е. чтобы сообщения валидации были "человеческими"

**Comment by fey** [comment]
@xushaha как ваши успехи?

**Comment by fey** [comment]
@xushaha ничего страшного :)
Если вдруг вернетесь к выполнению - напишите.

**Comment by VasilyevPS** [comment]
Добрый день! Эта задача актуальная еще? Если да, я бы попробовал сделать.

**Comment by fey** [comment]
@VasilyevPS я думаю да, посмотрите по коду, берите в работу =)

**Comment by VasilyevPS** [comment]
@fey Николай, [PR 211](https://github.com/Hexlet/hexlet-correction/pull/211).
