### ISSUE TITLE
Bug: не локализована дата изменения/создания воркспейса

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#167]
![image](https://github.com/Hexlet/hexlet-correction/assets/697178/fceea59d-f857-48c2-a707-004b1f8eee4e)

**Comment by bikowskiy** [comment]
Добрый день! Могу взять в работу?

**Comment by biscof** [comment]
Привет! Беру в работу. Думаю ещё добавить отображение времени по часовому поясу пользователя в 24-часовом формате.

**Comment by fey** [comment]
Да, присылайте ПР и демку - посмотрим.

**Comment by biscof** [comment]
@fey Сделал ПР #224. Посмотрите, пожалуйста
