### ISSUE TITLE
Поправить отображение привязки опечатки к Workspace ID

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexlet-correction#174]
### Problem description

RКогда опечатка приходит в сервис, она привязывается к айдишнику воркспейса и этот айдишник отображается в колонке "Modified By". 

![image](https://github.com/Hexlet/hexlet-correction/assets/17835285/c2f9a156-a6a1-47d5-8c1d-542a75c4e92f)

### Proposed solution

Нужно убрать отображение айдишника, пока никто не работал с присланной опечаткой

**Comment by prozet-x** [comment]
@fey эта ишью тоже уже неактуальна, так?

**Comment by fey** [comment]
ага, щас id не выводится.
