### ISSUE TITLE
Убрать удаление опечатки

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexlet-correction#175]
### Problem description

Удаление присланной опечатки не нужно, лучше изменить его на "Архивирование"

### Proposed solution

.

**Comment by fey** [comment]
Актуально

**Comment by nuuska-muikkunen** [comment]
Тоже возьму? По сути тоже переименование, как и с OPEN.

**Comment by fey** [comment]
@nuuska-muikkunen Возьмите. Тут нужно проверить, что у нас физического удаления не будет

**Comment by nuuska-muikkunen** [comment]
Да, оказалось сложнее, т.к. там просто стоит активная кнопка на контроллер удаления.
Если мы не удаляем ошибку, то надо определиться, что стоит за словом "Архивирование":
- в какой статус ставить заархивированную опечатку
- надо ли и как отображать заархивированные ошибки
- надо ли иметь возможность зачем-то возвращать ошибку из архива и т.д. и т.п.

**Comment by fey** [comment]
По идее должен быть просто статус типа archived, такие ошибки будут выводиться если в просмотре специально их вывести (выбрать в фильтре). 
Пока не будет добавлять возможность восстановления

**Comment by nuuska-muikkunen** [comment]
@Malcom1986, ну как, попробую добавить новое состояние?
Это, конечно, не кнопки переименовывать. Тем более, что я только осваиваю thymeleaf (жаль, что не попал на новую версию курса, где обещают ему учить).

**Comment by nuuska-muikkunen** [comment]
У меня вопрос: это правильно прописать конкретные имена констант enum в dbchangesets?
Чтобы это изменить мне надо углубиться в изучение liquibase иначе новый статус ARCHIVE не добавить.
То есть на кнопках он есть, но некоторые тесты не проходят и перейти в этот статус не получается - ошибка SQL, т.к. такое значение enum отсутствует.

**Comment by fey** [comment]
а enum на уровне БД?

**Comment by fey** [comment]
посмотрел, енам действительно на уровне бд :thinking: 
Я бы предложил дропнуть енам. По сути везде, где мы использеум стейты, мы испольуезм конечные автоматы, а в бд они в виде обычной строки.
С другой стороны, если мы добавляем новый стейт, то по сути задача тут в том, чтобы обновить енам.

**Comment by fey** [comment]
@nuuska-muikkunen я подумал, давайте не будем добавлять состояния CANCELLED. Давайте просто его использовать. 
Т.е. задача в том, чтобы убрать кнопки удаления, роуты

**Comment by nuuska-muikkunen** [comment]
1) Новое событие ARCHIVE добавляется одной строкой: ALTER TYPE TYPO_STATUS ADD VALUE 'ARCHIVE'
Мне бы получить совет как выполнить обновление, если база запущена в докере, а в параметрах liquidbase update в ubuntu должен быть url доступа к базе. Как дотянуться к postgres'у через psql мне понятно, а как туда ссылку сконструировать?
2) Прошу уточнить про CANCELLED. Во-первых, это статус, а не состояние. Во-вторых, состояние CANCEL уже существует. В-третьих, мы вроде состояние ARCHIVE добавляли, чтобы заменить кнопку DELETE с "терминальной" функцией удаления - после этого никаких статусов и обработки не предусматривалось.
3) Конечно, можно придумать работу в статусе CANCELLED (кроме возможности возврата к обработке ошибки). Но если просто убрать кнопку и обработку ее маршрута (роута), то где будем удалять обработанные ошибки? База будет расти. а контроллера с очисткой не будет. Может CANCEL где-то будет удалять?

Извините за сумбур.

P.S. пожалуйста,не забудьте посмотреть переименование кнопки OPEN (№177) на рендере. Если ок, то я почищу код от комментов и сделаю финальный коммит для ревью.

**Comment by nuuska-muikkunen** [comment]
Снимаю вопрос по п. 1) (хотя пока не работает, но синтаксис проходит и url определился).

**Comment by fey** [comment]
то, что будет база расти - это нормально. В реальной жизни многие проекты физически не удаляют даныне из бд, а помечают их удаленными. Особенно обработанные ошибки - они ведь могут потребоваться для аналитики, например.
Стейт = статус в данном случае. Просто убираем удаление вообще, если нужно фильтровать опечатки, то есть статус. Т.е. нам и новый статус не нужен, а задача заключается просто в удалении кнопки и контроллеров. Пока как-то по особому опечатки не будем обрабатывать.

**Comment by fey** [comment]
```Новое событие ARCHIVE добавляется одной строкой: ALTER TYPE TYPO_STATUS ADD VALUE 'ARCHIVE'
Мне бы получить совет как выполнить обновление, если база запущена в докере, а в параметрах liquidbase update в ubuntu должен быть url доступа к базе. Как дотянуться к postgres'у через psql мне понятно, а как туда ссылку сконструировать?```

если база у вас в докере запускается, а приложение локально - то просо в прописываете нужный коннект. Для приложения неважно где будет база. Изменения в базу добавляются через миграции данных. Не знаю, как в джаве, в других языках/фреймворках пишется новый файлик миграции и там, что нужно сделать. например обновить енам.

```Прошу уточнить про CANCELLED. Во-первых, это статус, а не состояние. Во-вторых, состояние CANCEL уже существует. В-третьих, мы вроде состояние ARCHIVE добавляли, чтобы заменить кнопку DELETE с "терминальной" функцией удаления - после этого никаких статусов и обработки не предусматривалось.```

хорошо, если архивед добавили - давайте использовать. Тут нужно по смыслам исходить, какой статус за что отвечает. К сожалению, докуменатции проекта нет, продукт менеджера нет (точнее есть, но есть нюанс), поэтому что-то придется самим выдумывать. 

По сути cancelled -  это все, что нам нерелвантно. Аналог удаления, но не совсем. Архив - это то, что удалено, в мусорной корзине. С точки зрения пользователя - отменненная опечатка и архивная - чем они будут отличаться? :thinking: 

> Конечно, можно придумать работу в статусе CANCELLED (кроме возможности возврата к обработке ошибки). Но если просто убрать кнопку и обработку ее маршрута (роута), то где будем удалять обработанные ошибки? База будет расти. а контроллера с очисткой не будет. Может CANCEL где-то будет удалять?

тут я уже предыдущим сообщением ответил. Переживать за базу не стоит. Нам даже до 1к строк в оечатках очень далеко

**Comment by nuuska-muikkunen** [comment]
Приношу мои извинения, замотался с работой.
1) Отдельно стоящую кнопку Delete под которой стоит контроллер, удаляющий опечатку, можно легко удалить. Это отдельный фрагмент кода.
Нужно ли в принципе удалять и контроллер, включая сервисный слой и проч.?
2) Будем ли добавлять статус ARCHIVED?
a) будет ли его поведение последней инстанцией: только просмотр и нет возможности вернуться к обработке или удалить.
3) Будем ли что-то делать со статусом CANCELLED?
А именно:
а) переименовывать в ARCHIVED
б) менять в связи с этим его поведение
4) Мне кажется, что CANCELLED - это когда ошибка определена неправильно или сформулирована непонятно и мы отбиваем ее, оставляя возможность возврата к обработке, если кто-то пришлет ее повтор, обоснует или объяснит ее суть и необходимость исправления, а статус ARCHIVED - это когда ошибка обработана или окончательно безнадежна и не подлежит обработке.
Тогда таки буду добавлять такой ARCHIVED и не буду трогать CANCELLED.

**Comment by fey** [comment]
Давайте пока условимся, что у нас нет удаления. А если нужно ошибку игнорировать (ошибочная и тд), то пусть пользователи используют именно cancel. Тогда нам новый статус не нужен, кода будет меньше.

**Comment by nuuska-muikkunen** [comment]
Создал pool request. Приложение (и отсутствие кнопки Delete) можно посмотреть там же на рендере https://hexlet-correction-rqc5.onrender.com/ В процессе удалил строки на фронте с кнопкой, соответствующий контроллер, сервис и еще несколько тестов.

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-correction/pull/241
