### ISSUE TITLE
Rename the Open button

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexlet-correction#177]
### Problem description

It is unclear what the Open button does in the sent typo

### Proposed solution

Since this button translates the typo to the status "In progress", you can rename it to "Start work" or "Get started"

**Comment by fey** [comment]
Актуально

**Comment by nuuska-muikkunen** [comment]
Привет!
Я заканчиваю курс и хочу попробовать смогу ли разобраться в коде.

**Comment by fey** [comment]
Да, берите.

**Comment by nuuska-muikkunen** [comment]
Имя кнопки OPEN определяется именем константы OPEN перечисления TypoEvent. В зависимости от этих констант (OPEN, RESOLVE, REOPEN, CANCEL) меняется статус переданной опечатки, задается имя кнопки и ее цвет.
1) Будем переименовывать OPEN в START WORK (я бы лучше переименовал просто в START)?
2) Надо ли, следуя нашей логике, переименовать константу REOPEN в RESTART (RESTART WORK)?
3) Имена методов тестирования тоже переименовывать (patchTypoEventOpenToReported и patchTypoEventReopenToCanceled)?

PS Спрашиваю, поскольку у меня это первый опыт работы с незнакомым кодом.

**Comment by fey** [comment]
@Malcom1986 поможешь нам?
Скорее всего по коду тоже нужно поменять, ведь у нас и смыслы меняются.

**Comment by Malcom1986** [comment]
@nuuska-muikkunen Приветствую. Давайте сами состояния трогать не будем, оставим как есть. Они довольно семантично называются. Поменяем только надпись на кнопке, сделаем ее более юзер френдли

**Comment by nuuska-muikkunen** [comment]
Состояния не трогаю. Только названия ивентов, от которых названия кнопок определяются.
Вместо OPEN - START, вместо REOPEN - RESTART.
На русском: вместо ОТКРЫТЬ - НАЧАТЬ, вместо ОТКРЫТЬ ЗАНОВО - НАЧАТЬ СНОВА.

**Comment by nuuska-muikkunen** [comment]
Вот так выглядят новые кнопки (см прилагаемые скринки экранов с локального запуска приложения).
[result of screens  issue #177 button OPEN rename.pdf](https://github.com/Hexlet/hexlet-correction/files/14704632/result.of.screens.issue.177.button.OPEN.rename.pdf)
Можно коммитить? Изменения в отдельной ветке.

**Comment by fey** [comment]
Вы можете запушить в свою ветку и создать пулл реквест
https://www.youtube.com/watch?v=pUT3mx1ZRUM
Пока ПР не принят, в него можно спокойно вносить изменения. При принятии ПРа будут приняты изменения на момент принятия. Скрин не могу посмотреть, он в формате ПДФ. Лучше задеплойте демо и скиньте ссылку на посмотреть.

**Comment by nuuska-muikkunen** [comment]
Деплой не проходит. У вас Dockerfile не менялся 9 месяцев и все про Maven, а POM file убрали при миграции на gradle. Я правильно понял?

**Comment by Malcom1986** [comment]
Да, здорово будет, если и докерфайл поправите заодно. Можно в Procfile подглядывать, как мы заускаем приложение на хероку

**Comment by nuuska-muikkunen** [comment]
Наконец победил деплой :-)
Можете смотреть результат https://hexlet-correction-rqc5.onrender.com/.
У меня требуется VPN для работы.
