### ISSUE TITLE
Доработать вкладку Integration

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexlet-correction#178]
### Problem description

Вкладка Integration неактивна и непонятно для чего она нужна, скрипт для подключения находится на вкладке "Settings"

### Proposed solution

Переместить скрипт для подключения во вкладку "Integration", во вкладке "Settings" оставить регенерацию токена. 
Кнопку регенерации токена сделать доступной только для админа воркспейса

**Comment by VasilyevPS** [comment]
Возьму в работу
