### ISSUE TITLE
Добавить возможность удаления пользователей из воркспейса

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexlet-correction#179]
### Problem description

Можно добавлять пользователей в свой воркспейс, но удалять нельзя, даже ошибочно добавленных.

### Proposed solution

Добавить возможность отключать пользователей от воркспейса, но только для админа

**Comment by AlekseyNechunaev** [comment]
Привет, беру в работу

**Comment by AlekseyNechunaev** [comment]
Отдал PR https://github.com/Hexlet/hexlet-correction/pull/183
