### ISSUE TITLE
Bug: Проблемы при авторизации пользователя в Username которого буквы верхнего регистра 

### ISSUE THREAD

**Issue by kairina2020** [Hexlet/hexlet-correction#189]
### Summary

Успешно зарегистрирован пользователь в Username которого есть буквы верхнего регистра. При авторизации, если Username  написан только буквами нижнего регистра, то выдается ошибка "Bad credential".
Данные зарегистрированного пользователя:
uSer_22 (Username)
Test3@tu.tu
Ir K
U&s-e^r`Э\ (пароль содержит в конце символ)

### Reproduction steps

```bash
1. https://hexlet-correction.herokuapp.com/login
2. В поле Username вводим 'user_22'
3. В поле Password 'U&s-e^r`Э\ '
4. Кнопка 'Login'
```

### Expected result

Происходит успешная авторизация  пользователя 

### Actual result

Выдается сообщение "Bad credential"

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
нет, это баг. почта действительно одна и та же. И регистр символов должен игнорироваться.

**Comment by AlekseyNechunaev** [comment]
Беру в работу

**Comment by kairina2020** [comment]
@fey протестирую сегодня

**Comment by kairina2020** [comment]
@fey 
Успешно зарегистрирован пользователь в Username которого есть буквы верхнего регистра. При авторизации, если Username написан только буквами ниж
![image](https://github.com/Hexlet/hexlet-correction/assets/110185387/14365775-164c-42d8-a1a6-2d7731505d6d)
него регистра, то выдается ошибка "Bad credential". - эта ошибка осталась.

**Comment by fey** [comment]
@kairina2020 протестируйте. пожалуйста, новую версию - https://hexlet-correction-test.onrender.com/
Комментарии можно передать сюда - https://github.com/Hexlet/hexlet-correction/pull/192

**Comment by kairina2020** [comment]
https://hexlet-correction-test.onrender.com/ по данной ссылке у меня открывается это окно, 
![image](https://github.com/Hexlet/hexlet-correction/assets/110185387/8af5d545-cf92-4418-b6e7-5e2cbde6b41f)
Тут что-то нужно сделать, чтобы перейти на сайт?

**Comment by fey** [comment]
@kairina2020 да, все верно. это другая версия с фиксом регистрации. ниже прокрутите и там будет кнопка для регистрации

**Comment by prozet-x** [comment]
@fey что с этой задачей?
В данный момент дело обстоит так: при регистрации вводим юзернейм нового пользователя в любом регистре, а в базу оно пишется в нижнем. Если потом попробовать зарегать нового юзера с таким же юзернеймом, при этом как угодно меняя регистр, то регистрация не получится - ругается на то, что уже есть юзер с таким юзернеймом.
Верно понимаю, что эта ишью не актуальна? Если понимаю неверно, то поясните, чего нужно наваять?
