### ISSUE TITLE
Символы, принимаемые при регистрации в поле Password  (Это не кажется правильным)

### ISSUE THREAD

**Issue by kairina2020** [Hexlet/hexlet-correction#190]
При регистрации пользователя в поле  Password успешно принимаются буквы русского алфавита, пароль может начинаться с символа "-", в пароле первым и последним символом может быть пробел.

**Comment by kairina2020** [comment]
@fey , а по паролю тоже посмотри.

**Comment by fey** [comment]
символ `-` это ок. Насчет кириллицы - возможно неправильно. Проббельных символов в пароле не должно быть. (даже в середине пароля)

**Comment by prozet-x** [comment]
@fey эта задача тоже уже неактуальна, верно?

**Comment by fey** [comment]
Здесь нужен чек от тестировщиков.

**Comment by prozet-x** [comment]
@kairina2020 можно попросить Вас проверить?

**Comment by fey** [comment]
гуд, тогда можем закрывать.
