### ISSUE TITLE
Реализовать аутентификацию на сайте по email пользователя

### ISSUE THREAD

**Issue by Malcom1986** [Hexlet/hexlet-correction#193]
### Problem description

Сейчас вход на сайт осуществляется по Username пользователя. Кажется, что более удобным вариантом будет использовать в качестве логина Email пользователя, так как он по определению уникальный

### Proposed solution

Сделать вход на сайт по email вместо имени пользователя

**Comment by MarkDementev** [comment]
Задачу принял.

**Comment by fey** [comment]
@MarkDementev ривет. Как успехи? Нужна помощь?

**Comment by prozet-x** [comment]
@fey , задача, я так понимаю, свободна? Если да, то дайте её мне.
Эта задача, кажется, взаимосвязана с еще двумя другими: [195](https://github.com/Hexlet/hexlet-correction/issues/195) и [196](https://github.com/Hexlet/hexlet-correction/issues/196) . Давайте их все? Думаю, так проще будет - разом все сделать, нежели на куски работу рвать.
В принципе, я уже тут по этим трем задачам кой-чего сделал. Но надо бы, чтобы предварительно глянули - верной ли дорогой иду.
Потыкать можно [тут](https://hexlet-correction-r29m.onrender.com).

**Comment by fey** [comment]
По декомпозиции можно у @Malcom1986 спросить. А так да. Выглядит свободной.

**Comment by fey** [comment]
Но надо чекнуть что еще осталось

**Comment by prozet-x** [comment]
@fey , пулл-реквест отправил. [Тут](https://github.com/Hexlet/hexlet-correction/pull/229).
@Malcom1986 , окинь своим критическим взором, что я там настряпал, пжлст.
Правки в основной ветке сделал. Или все же лучше отдельно впредь делать?

**Comment by fey** [comment]
лучше делать в отдельной ветке - вам будет проще стягивать изменения из основного репозитория, если в нем что-то появится. 
Функционал чуть поозже гляну. По коду Максим посмотрит =)

**Comment by prozet-x** [comment]
Ок, понял.

**Comment by prozet-x** [comment]
@fey , Максим [принял PR](https://github.com/Hexlet/hexlet-correction/pull/229).
