### ISSUE TITLE
Добавить тесты на удаление пользователя из воркспейса

### ISSUE THREAD

**Issue by Malcom1986** [Hexlet/hexlet-correction#194]
### Problem description

Была добавлена возможность удаления пользователя из воркспейса. Но теста на эту фичу нет

### Proposed solution

Дописать тест на удаление пользователя из воркспейса

**Comment by kudrDaniel** [comment]
Возьму в работу

**Comment by fey** [comment]
@kudrDaniel привет. Как успехи? Нужна помощь?

**Comment by prozet-x** [comment]
@fey , задача свободна? Вроде, сваял тест. Могу PR отправить.

**Comment by fey** [comment]
Ага, свободна

**Comment by prozet-x** [comment]
@fey Максим применил изменения.
