### ISSUE TITLE
Добавить тест на то, что при регистрации и логине не учитывается регистр email

### ISSUE THREAD

**Issue by Malcom1986** [Hexlet/hexlet-correction#195]
### Problem description

Email по стандарту является регистронезависимым. При регистрации нового пользователя и при логине регистр почты не учитывается. Нужно написать тест, который будет проверять это

### Proposed solution

Написать тест на то, что при регистрации и входе в систему не учитывается регистр символов в email

**Comment by MarkDementev** [comment]
Задачу принял.

**Comment by prozet-x** [comment]
@Malcom1986 , [этот](https://github.com/Hexlet/hexlet-correction/pull/229) PR Вы приняли. Там текущая ищью тоже ведь была решена. По крайней мере, я старался это там сделать) Может, тогда эту задачу закрыть?

**Comment by prozet-x** [comment]
@fey гляньте, пжлст. Выше я написал. Кажется, эта ишью не актуальна более?

**Comment by fey** [comment]
@Malcom1986 Макс, можешь чекнуть
