### ISSUE TITLE
Bug: При регистрации с несовпадением Email и подтверждения в разных регистрах

### ISSUE THREAD

**Issue by kairina2020** [Hexlet/hexlet-correction#196]
### Summary

Когда при регистрации вводишь адрес Email  и подтверждаешь и они отличаются  только регистром символов, то регистрация не происходит, для программы это 2 разных электронных адреса.
А это насколько понимаю один и тот же адрес электронной почты считается. 

Тестовые данные:
Username = Ilona4
Email = test1@tu.tu
First Name = i
Last Name = i
Password = 12345678

### Reproduction steps

```bash
• 1 Ввести Username
• 2 Ввести Email     "test1@tu.tu"
• 3 Подтвердить Email "Test1@tu.tu"
• 4 Ввести First Name/Имя
• 5 Ввести Last Name/Фамилию
• 6 Ввести Пароль
• 7 Подтвердить Пароль
• 8 Нажать кнопку Create Account/Зарегистрироваться
```

### Expected result

Пользователь успешно зарегистрирован.

### Actual result

Пользователь НЕ зарегистрирован. При нажатии на кнопку Зарегистрироваться появляется сообщение "Пароль и подтверждения должны совпадать"

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
Подтверждение пароля выглядит лишним - стоит убрать.

**Comment by prozet-x** [comment]
Если в рамках этой задачи нужно было дать возможность при регистрации указывать почту и её подтверждение с несовпадающими по регистру символами, то это было сделано, кажется.
@Malcom1986 , [этот](https://github.com/Hexlet/hexlet-correction/pull/229) PR Вы приняли. Там и эта ищью тоже ведь была решена. По крайней мере, я старался это там сделать) Может, тогда и эту задачу закрыть тоже?

**Comment by fey** [comment]
@kairina2020 можете проверить, исправлено ли?

**Comment by kairina2020** [comment]
Добрый день! Да, конечно, сегодня- завтра гляну отпишусь

**Comment by kairina2020** [comment]
@fey, Николай, добрый вечер!
Подскажите, пожалуйста, интерфейс не изменился, также требуется подтверждение эл.почты?
Скрин прикладываю.
Если не изменился, то данная проблема "Регистрозависимость адреса электронной посты при подтверждении адреса электронной почты" решена.
Фактический результат и ожидаемый совпадают: регистрация пользователя происходит. 

![image](https://github.com/Hexlet/hexlet-correction/assets/110185387/abaffa9c-bf94-4030-9381-c1ff950e9963)

**Comment by fey** [comment]
а, понял @prozet-x давайте уберем конфирм электронной почты. Это выглядит лишним. Достаточно один раз ввести почту + проверять ее регистронезависимо

**Comment by prozet-x** [comment]
@fey Обычно на сайтах почту просят продублировать при регистрации, чтобы исключить очепятки, кмк. Точно убрать конфирм для почты?

**Comment by fey** [comment]
Да, давайте убирать. Конфирм почты я редко встречаю 
![image](https://github.com/Hexlet/hexlet-correction/assets/697178/1231722b-e2f9-4a03-8240-0b22148dd9f7)

**Comment by prozet-x** [comment]
@fey конфирм убрал. PR [тут](https://github.com/Hexlet/hexlet-correction/pull/231)

**Comment by prozet-x** [comment]
@kairina2020 если можно, проверьте, пожалуйста.

**Comment by kairina2020** [comment]
@prozet-x , Дмитрий, Добрый день! Вчера пыталась перейти по ссылке "потыкать" новый конфирм, не получилось открыть. Есть ещё какой-то вариант перехода?

**Comment by prozet-x** [comment]
@kairina2020 [PR](https://github.com/Hexlet/hexlet-correction/pull/231) принят, а соответствующую ветку я уже удалил. Потыкать можно прямо в самом сервисе по [ссылке](https://fixit.hexlet.io/signup).
Если надо, могу, конечно, и отдельно поднять на Render копию.

**Comment by kairina2020** [comment]
@prozet-x , ок. Оказывается я вчера потестила старую версию. Нужно на всякий случай потестить и тут)

**Comment by kairina2020** [comment]
@fey , @prozet-x , Добрый вечер!
Прошла те же 4 теста на новой форме регистрации, по ссылке  https://fixit.hexlet.io/workspaces

**1. Позитивный. Адрес электронной почты корректный.**
   - ожидаемы результат "Пользователь прошел регистрацию"
   - Фактический  - пользователь зарегистрирован (Совпадает с ожидаемым)_
   
Рисунок 1 - входные данные, рисунок 2 - фактический результат  
![Test8](https://github.com/Hexlet/hexlet-correction/assets/110185387/f0a7a301-5c4a-4a46-83c4-e34ba3731c2c)
![Test8_fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/7050a9c5-83ec-4ce2-aee1-135d32b498a8)

**2. Негативный. Адрес электронной почты некорректен. Отсутствует  @**
   - ожидаемы результат "Пользователь не зарегистрирован"
   - Фактический  - пользователь не зарегистрирован (Совпадает с ожидаемым)_
   
Рисунок 1 - входные данные, рисунок 2 - фактический результат  
![Test5](https://github.com/Hexlet/hexlet-correction/assets/110185387/04ac929b-3ba2-4637-bfd2-f78e4109df15)
![Test5_fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/ecbf792d-ef34-4f03-b6d7-3f26497d7126)

**3. Негативный. Адрес электронной почты некорректен. Отсутствует часть ПОСЛЕ знака точка*
   - ожидаемы результат "Пользователь не зарегистрирован"
   - Фактический  - пользователь не зарегистрирован (Совпадает с ожидаемым)_
   
Рисунок 1 - входные данные, рисунок 2 - фактический результат 
![Test7](https://github.com/Hexlet/hexlet-correction/assets/110185387/8f0b1a30-2afb-404a-8676-46512283e192)
![Test7_fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/53526374-d1f3-45a4-b2dd-b95bf2f20c4c)

**4. Негативный. Адрес электронной почты некорректен. Отсутствует часть ДО знака точка*
   - ожидаемы результат "Пользователь не зарегистрирован"
   - Фактический  - пользователь не зарегистрирован (Совпадает с ожидаемым)_
   
Рисунок 1 - входные данные, рисунок 2 - фактический результат 
![Test6](https://github.com/Hexlet/hexlet-correction/assets/110185387/6c916fdd-02b0-4dc9-9e65-027034841477)
![Test6_fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/4f7bbd7b-52a0-4087-9291-60b5a680f3ce)

Итог, регистрацию можно пройти только только с корректным адресом электронной почты.

**Comment by fey** [comment]
Ну шо, можно закрывать?)

**Comment by kairina2020** [comment]
На мой взгляд с новой формой он не актуален)

**Comment by fey** [comment]
Отлично!
