### ISSUE TITLE
Bug: При регистрации, если указана не полностью электронная почта, нет части доменного имени (.код страны)

### ISSUE THREAD

**Issue by kairina2020** [Hexlet/hexlet-correction#197]
### Summary

#1192 Проверка регистрации с неверным Email, отсутствует часть домена, код страны
При указании электронной почты с ошибкой в виде user_2023@tu и подтверждении user_2023@tu, например путем копирования. Происходит успешная регистрация пользователя, чего быть не должно

Тестовые данные:
Username = Ilona
Email = user_2023@tu
First Name = i
Last Name = i
Password = 12345678

### Reproduction steps

```bash
Тестовые данные: 
• 1 Ввести Username
• 2 Ввести Email   "user_2023@tu"
• 3 Подтвердить Email    "user_2023@tu"
• 4 Ввести First Name/Имя
• 5 Ввести Last Name/Фамилию
• 6 Ввести Пароль
• 7 Подтвердить Пароль
• 8 Нажать кнопку Create Account/Зарегистрироваться
```

### Expected result

Пользователь НЕ должен быть зарегистрирован

### Actual result

Происходит успешная регистрация пользователя

### Browsers

Chrome

### OS

Windows

**Comment by kudrDaniel** [comment]
Возьму в работу.

**Comment by kudrDaniel** [comment]
@fey можно закрывать issue?

**Comment by kairina2020** [comment]
@fey, Протестирую сегодня

**Comment by fey** [comment]
Отлично, тогда ждем результата

**Comment by kairina2020** [comment]
Добрый вечер! Проблема решена. 
При выполнении теста:
Страница регистрации :https://hexlet-correction.herokuapp.com/signup
В тесте использовался не зарегистрированный Username: Ilon
Не зарегистрированный E-mail: user_2024@tu

**Фактический результат:** Пользователь не зарегистрирован.
Выводится сообщение "The email "Email" incorrect" (Электронная почта не верна)

**Expected result**
Пользователь НЕ зарегистрирован.
При нажатии на кнопку Зарегистрироваться появляется сообщение "Неверный адрес Email"

![Issues#197](https://github.com/Hexlet/hexlet-correction/assets/110185387/c5841cf4-aba5-401b-be51-c0e4dcfb00b4)

**Comment by prozet-x** [comment]
@fey эта задача уже неактуальна, верно?

**Comment by fey** [comment]
Чтобы ответить на вопрос, мне надо понять, а с каким емейлом щас можно регаться, а с каким нельзя?) Ну чтобы кто-то из тестировщиков отметил, повторяется ли баг.

**Comment by kairina2020** [comment]
@fey , сегодня гляну

**Comment by kairina2020** [comment]
Добрый вечер! 
Тесты проводились на странице регистрации :https://hexlet-correction.herokuapp.com/signup

Проверяла 4 варианта:
1. Позитивный, с корректным адресом электронной почты.
 - ожидаемый результат - Пользователь зарегистрирован
 -  фактический результат  - Пользователь зарегистрирован. _(Соответствует ожидаемому)_
 
 Рисунок 1 - входные данные, рисунок 2 - фактический результат
![Test4](https://github.com/Hexlet/hexlet-correction/assets/110185387/3e7c9171-6f0d-435b-b963-b8c93be23541)
![Test4_fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/6c819d9f-baf4-4aaa-a852-a2adefe30284)

2. Негативный, некорректный адрес электронной почты (отсутствует часть адреса после знака "@").
 - ожидаемый результат - Пользователь не зарегистрирован. Сообщение, что адрес некорректный
 -  фактический результат  - Пользователь не зарегистрирован, есть поясняющее сообщение. _(Соответствует ожидаемому)_
  
 Рисунок 1 - входные данные, рисунок 2 - фактический результат
![Test3](https://github.com/Hexlet/hexlet-correction/assets/110185387/eeaa72f8-84a9-4ca6-8ae8-c49e54a9f515)
![Test3_Fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/25acf1f6-aa72-4539-8dc3-e9068514c532)

3. Негативный, некорректный адрес электронной почты (отсутствует часть доменного имени "ДО разделяющей точки").
 - ожидаемый результат - Пользователь не зарегистрирован. Сообщение, что адрес некорректный
 -  фактический результат  - Пользователь не зарегистрирован, есть поясняющее сообщение. _(Соответствует ожидаемому)_
  
 Рисунок 1 - входные данные, рисунок 2 - фактический результат
![Test1](https://github.com/Hexlet/hexlet-correction/assets/110185387/9ba7b7dd-4a7e-45e4-bce2-eb3502224353)
![Test1_fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/ee38cfca-79a5-4658-bfea-80e629ed2b59)

4. Негативный, некорректный адрес электронной почты (отсутствует часть доменного имени "ПОСЛЕ разделяющей точки").
 - ожидаемый результат - Пользователь не зарегистрирован. Сообщение, что адрес некорректный
 -  фактический результат  - Пользователь не зарегистрирован, есть поясняющее сообщение. _(Соответствует ожидаемому)_
  
 Рисунок 1 - входные данные, рисунок 2 - фактический результат
![Test2](https://github.com/Hexlet/hexlet-correction/assets/110185387/412fcdfc-9133-418e-8392-5930b7e5ec72)
![Test2_Fakt](https://github.com/Hexlet/hexlet-correction/assets/110185387/91808576-e327-4769-9d80-bdad9815b4e5)

**Comment by fey** [comment]
Супер! Тогда закрываем ищщус.
