### ISSUE TITLE
Refactor the project to reflect changes in hexlet-components/java-spring-blog

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#199]
### Problem description

Kirill Mokevnin updated boilerplate and approaches in Java course, accordingly updated boilerplate. There appeared a lombok, in gradle - Kotlin config and so on

### Proposed solution

Start migrating the project to a new rake based on what's inside hexlet-components/java-spring-blog

**Comment by dariakoval** [comment]
я правильно понимаю, нужно pom.xml переделать в build.gradle.kts, добавить зависимость ломбок и прочие новые зависимости из hexlet-components/java-spring-blog?
если да, то я возьмусь

**Comment by fey** [comment]
Кажется что да, @Malcom1986 подскажешь Дарье?)

**Comment by Malcom1986** [comment]
Да и в целом использовать те подходы, которые мы в курсе рассматриваем

**Comment by dariakoval** [comment]
хорошо, взяла в работу)

**Comment by fey** [comment]
Помните, что это большая задача, поэтому тут нормально в несколько небольших ПРов вносить изменения.

**Comment by fey** [comment]
Актуально.

**Comment by funnyDevGirl** [comment]
Приветствую.

Насколько актуальная задача, и что требуется на данный момент?)

**Comment by fey** [comment]
Кажется это актуальна. К сожалению, собрать список того, что нужно не получится. Но вы можете стартануть и потихоньку делать. На градл переехали, а вот всякие новые штуки, которые у нас стали использоваться - вроде бы нет, не сделали.

**Comment by Grad566** [comment]
Hi!
What do you mean by:
"а вот всякие новые штуки, которые у нас стали использоваться - вроде бы нет, не сделали."

**Comment by fey** [comment]
Maksim: We can close it, it is no longer relevant. Gradle has moved to gradle, it was the most important part. Automatic mapping from dto to essence is used there, lombok too
