### ISSUE TITLE
Проблемы при изменении данных пользователя в профиле

### ISSUE THREAD

**Issue by kairina2020** [Hexlet/hexlet-correction#200]
@fey , Тестировала профиль пользователя на внесение в него изменений. 
Опишу в общем проблемы, которые встретились. Они повторяют те, что были при регистрации, поэтому сразу обратите внимание на них при внесении изменений.
1.  На мой взгляд подтверждение Email тут лишнее, так как при изменении любого из параметров, будь-то Username, фамилия имя или  Email, каждый раз приходится вводить подтверждение адреса электронной почты. Велика вероятность ошибиться и неудобно.
2.  E-mail и его подтверждения остались регистрозависимыми, достаточно одной букве быть в  другом регистре, сразу несовпадение.
3. Позволяет успешно изменять верный Email на неверный/неполный по шаблону %@%  без точки и кода страны.
4. Заметила одну проблему, редко проявляется, возможно не критично, но для информации. 
При изменении Username, если измененный уже зарегистрирован в системе, то появляется сообщение об этом, 
НО иногда  все же изменить можно на уже зарегистрированный.
Проявляется редко, логику не получилось понять. 
Думала зависит от того, проходила ли полная регистрация с этим Username или только редактировался в профиле пользователя, но нет, НЕ зависит.

**Comment by fey** [comment]
@TonyMudRec здесь описаны несколько задач. Я предлагаю идти поэтапно. Давайте сперва поправим валидацию.

**Comment by fey** [comment]
@kairina2020 можете описать поэтапно, как вы обновляли профиль? Я сейчас попробвоал и получаю ошибку 
![image](https://github.com/Hexlet/hexlet-correction/assets/697178/966a1625-598c-4d60-a11d-3e79c5bc53d3)

**Comment by TonyMudRec** [comment]
пока не буду брать

**Comment by fey** [comment]
Пардон, я не тот проект посмотрел :facepalm:

**Comment by fey** [comment]
> На мой взгляд подтверждение Email тут лишнее, так как при изменении любого из параметров, будь-то Username, фамилия имя или Email, каждый раз приходится вводить подтверждение адреса электронной почты. Велика вероятность ошибиться и неудобно.

да, по идее информация о пользователе может быть разделена, на профиль и инфу об аккаунте. Например как в Хекслете это сделано.

```E-mail и его подтверждения остались регистрозависимыми, достаточно одной букве быть в другом регистре, сразу несовпадение.
Позволяет успешно изменять верный Email на неверный/неполный по шаблону %@% без точки и кода страны.```

ага, валидация должна быть везде одинаковой.

**Comment by fey** [comment]
```При изменении Username, если измененный уже зарегистрирован в системе, то появляется сообщение об этом,
НО иногда все же изменить можно на уже зарегистрированный.
Проявляется редко, логику не получилось понять.
Думала зависит от того, проходила ли полная регистрация с этим Username или только редактировался в профиле пользователя, но нет, НЕ зависит.```

по идее юзернейм может быть неуникальным, хм. Мы пока нигде не выводим юзернеймы, но надо это будет чекнуть.
