### ISSUE TITLE
Bug: При добавлении пользователя к существующему воркспейсу, предлагается список из всех зарегистированных пользователей

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#203]
### Summary

Кажется это что-то нежелательное, так как в последствие пользователей будет сильно больше и показывать их всех нет никакой необходимости

![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/0861f03e-bc7c-4c0e-a6f2-bdc04132a9c9)

### Reproduction steps

```bash
1. Открываем вкладку Users
2. Нажимаем на выпадающий список Email (над кнопкой Add to workspace)
```

### Expected result

Ввод email пользователя самостоятельно, дальше сервис проверяет существование пользователя, высылает ему инвайт. Если инвайт принят, то пользователь добавляется в список.

### Actual result

Список всех пользователей

### Browsers

Microsoft Edge

### OS

Windows

**Comment by fey** [comment]
Изменить поле - заменить поле на инпут, в котором можно прописать пользователя. Если такой пользователь есть, он будет приглашен в воркспейс.

**Comment by sushilyaz** [comment]
Готов взяться, но есть вопрос по развертыванию
