### ISSUE TITLE
Feature request: Сделать глобальный handler для обработки исключений

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#204]
### Problem description

На данный момент обработка исключений реализована через try-catch в каждом контроллере, что немного захламляет логику контроллера и периодически приводит к повторению кода

### Proposed solution

Сделать глобальный handler для обработки исключений, возникающих в контроллерах. Для примера можно посмотреть как это сделано в [эталонном проекте по Spring ](https://github.com/hexlet-components/java-spring-blog/blob/main/src/main/java/io/hexlet/blog/handler/GlobalExceptionHandler.java) или в [моей реализации проекта](https://github.com/bazilval/my-task-manager/blob/main/src/main/java/hexlet/code/handler/CommonExceptionHandler.java)

**Comment by bazilval** [comment]
Готов и взяться за эту задачу

**Comment by fey** [comment]
@Malcom1986 пожалуйста, глянь, нужно ли это делать?

**Comment by Rasta341** [comment]
еще актуально? хочу попробовать

**Comment by Kukuru5a** [comment]
Возьму задачу

**Comment by fey** [comment]
@Kukuru5a Как успехи? Нужна помощь?
Задача актуальна. В уроках Хекслета мы про это рассказываем.

**Comment by Kukuru5a** [comment]
Создал отдельную ветку для хендлера, в которой внес все правки. Не могу выгрузить в репо. В какую ветку можно закомитить?
