### ISSUE TITLE
Feature request: Поправить сортировку опечаток

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#205]
### Problem description

1. Стрелочки у заголовков столбца отображаются постоянно, хотя должны быть только тогда, когда по конкретному столбцу необходима сортировка
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/06759ce0-431e-4770-9081-6bdf35e49b63)

2.  Вынести разметку заголовков с сортировкой в отдельный фрагмент, чтобы можно было прописать только что-то такое:
`<th th:replace="fragments/sorting :: sorting('id','Id')"></th>`
Это приведёт к снижению однотипной разметки, а также позволит переиспользовать её во всех таблицах (пользователей, воркспейсов)

### Proposed solution

1. Прописать в span содержащий стрелочку `th:if="${sortProp == 'columnName'}"`, а внутри оставить только проверку на направление сортировки.
В итоге как-то так:
`
<span th:if="${sortProp == 'modifiedBy'}">[[${sortDir.isAscending() ? '&uArr;' : '&dArr;'}]]</span>
`

Как должно выглядеть:
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/7796b239-2fb3-4ccc-9cf4-0cd844391c22)

2. Пример подобного решения:
[Вставка фрагмента](https://github.com/bezkoder/thymeleaf-pagination-sorting-example/blob/2681732ad81a22d183b23c91d4642140e640633e/src/main/resources/templates/tutorials.html#L63)
[Сам фрагмент](https://github.com/bezkoder/thymeleaf-pagination-sorting-example/blob/master/src/main/resources/templates/fragments/sorting.html)

**Comment by bazilval** [comment]
Если необходимо, то готов реализовать

**Comment by fey** [comment]
Мне кажется, тут должно как-то сложнее быть, точнее без рукопашки. Я пока не знаю как реализовано, я бы предложил посмотреть, есть ли библиотечки для удобной сортировки данных. Плюс сортировка по дефолту должна быть такая - сверху старые записи, внизу свежие

**Comment by bazilval** [comment]
Ну стрелочка как минимум точно не должна быть показана до тех пор, пока по конкретному критерию не происходит сортировка, а сейчас она показывается вообще у всех пунктов, что путает

Ну и это никак не конфликтует с сортировкой по умолчанию, наоборот, помогает её визуально сразу увидеть

**Comment by fey** [comment]
@bazilval некоторые задачи могут иметь разные решения. например в Хекслете когда-то в топе пользователей было больше 100 юзеров, была пагинация, которая сильно медленно работали. Вместо оптимизации кода тупо выключили пагинацию и оставили топ 100 юзеров. 

В целом можно посмотреть штуку с сортировкой, но тут есть некоторые нюансы
1) по идее мы переедем на api + react, отказавшись от шаблонизатора (но хз когда)
2) пока сервисом мало пользуются и фидбека не так много) Поэтому не выглядит сильно приоритетно
3) я бы еще изучил готовые решения, которые есть. Наверняка похожая задача кем-то решалась (а еще стрелочку бы заменил, чет она страшная)

**Comment by fey** [comment]
тут штука в том, что htmx не изучается в профессиях. По идее можно, но, если есть реакт, то зачем?)
Сделайте пулл реквест, посмотрим, что там со стрелчоками получится =)

**Comment by bazilval** [comment]
@fey чтобы у джавистов было больше разнообразной практики, я думал этот проект тут для этого. У фронтендеров такой возможности и так полно, кажется. Кстати, Thymeleaf теперь тоже нет в профессии :)

Пулл-реквест со стрелками сделаю, но после мержа предыдущего, потому что там те же строчки редактируются

**Comment by fey** [comment]
@fey да, по идее надо проект обновлять под новые технологии. Например и мавена нет - надо на градл переходить.
Просто вопрос целесообразности - зачем нам зоопарк :_)

**Comment by bazilval** [comment]
@fey ну как попытка оставаться в той же экосистеме, которая уже написана, просто добавить интерактивности с помощью HTMX. Особенно до того момента, пока нет ничего другого.

Ведь добавление фронта на React - это как раз создание отдельной кодовой базы, полная переработка существующего представления и так далее. Как-будто более многодельное что-то получается

Но опять же, если стоит задача добавить практики фронтам, то могу понять :)

**Comment by fey** [comment]
Ну тут такая штука, что java это больше работа с апи, чем с шаблонизатором. Просто в начале было проще сделать на шаблонизаторе все, чтобы было с чем работать. 
htmx можно добавить но...пока нет причин. Он может остаться, а на реакт будем переходить не скоро и в итоге нужно будет поддерживать это добро. В общем на такие вещи просто так не переходят.

**Comment by fey** [comment]
да, в некоторых проектах нет реакта, точнее он есть, но точечно. Например хекслет на 99% - это классический бекенд.
