### ISSUE TITLE
Feature request: Поправить пагинацию

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#206]
### Problem description

1. На данный момент нумерация листов идёт с нуля. Лучше нормализовать, а к отсчёту с нуля приводить уже на сервере, в обработчике
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/9c07a38a-4a18-4e9a-98ea-7298ae302b3d)

2. Не показывать переключатель количества листов, пагинацию и саму таблицу, если элементы отсутствуют
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/adfdc244-d887-42e8-b796-d30b5daa9033)

3. Слетает атрибут class у крайнего левого элемента пагинации при выставлении русского языка и переходе на любую страничку, отличную от первой
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/a5ddb272-2af6-42e6-bb8b-e27ec07d82e8)

### Proposed solution

1. Исправить обработку в контроллере

2. Проверка наличия элементов в коллекции через `<th:if>` в соответствующих тегах
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/032e7fc1-d7a4-433e-bd4a-61c3810fe207)

**Comment by bazilval** [comment]
Если необходимо, то готов реализовать

**Comment by fey** [comment]
Вижу у вас щас в работе другая задачка. Давайте ее доделаем, потому эту сделаем =)

**Comment by bazilval** [comment]
@fey привет, а как должно это работать? Если мы меняем фильтрацию, то не можем остаться на той же странице, так как у нас полностью меняется набор данных и страниц, соответственно

**Comment by fey** [comment]
@bazilval хм, а действительно. По идее так и должно быть, иначе нам придется выкручиваться и проверять, что такая-то страница существует. 
Предлагаю закрыть ищщус и оставить это задуманное поведение (по по идее тут не просто выбор статуса должен быть но и еще какие то поля + кнопка по типу "применить")

**Comment by bazilval** [comment]
@fey я подумал, что можно сделать немного другую штуку: в случае если у нас поведение по умолчанию не передавать эти данные в переменных пути (для сортировки – это дата по возрастанию, для количества – 15 опечаток, для страницы – первая, для статуса – все статусы)

Сейчас получается, например, путь https://fixit.hexlet.io/workspace/227/typos?page=0&size=15&sort=createdDate,ASC приведёт к тому же, что и https://fixit.hexlet.io/workspace/227/typos

**Comment by fey** [comment]
по идее выбор статуса должен быть общей частью фильтра. 
т.е. предположим, что мы хотим посмотреть опечатки по урлу, но только исправленные.  
Это конечно интерфейс надо переделывать, но тогда поведение не будет неожиданным. И в случае чего можно расширить фильтры (например добавить дату - от. до)
