### ISSUE TITLE
Bug: Сброс сортировки/фильтрации/размера страницы при смене статуса опечатки

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#208]
### Summary

Если находясь на страничке с опечатками, с настроенной сортировкой, размером страницы, фильтрацией, выбрать какую-либо из опечаток и нажать кнопку по смене её статуса, то происходит редирект на эту же страничку, но со сброшенными параметрами сортировки и прочим вышеупомянутым

Может как-то передавать эти данные? В теле запроса, например, а в принимающем контроллере уже подставлять в адрес редиректа

### Reproduction steps

```bash
1. Открыть страничку опечаток
2. Настроить сортировку, размер страницы
3. Выбрать задачу и нажать кнопку для смены статуса
```

### Expected result

Оказываемся на той же страничке, с теми же настройками сортировки и т.д.
Задача при этом сменила статус

### Actual result

Оказываемся на той же страничке, но все настройки сортировки и прочего сброшены

**Comment by TonyMudRec** [comment]
Возьму

**Comment by asidowner** [comment]
Актуально? Готов сделать

**Comment by fey** [comment]
@asidowner я думаю да, попробуйте воспроизвести =)

**Comment by asidowner** [comment]
Создал пулл реквест https://github.com/Hexlet/hexlet-correction/pull/235 @fey
