### ISSUE TITLE
Bug: Отображение окна репорта при увеличенном масштабе страницы

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#210]
### Summary

Если страничка браузера отображается в увеличенном масштабе, а мы пытаемся сделать репорт об опечатке, то всплывающее окно отображается обрезанным и прижатым к нижнему краю. Таким образом пользователю не видны кнопки управления:
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/2f77aab8-0ed5-4a75-a3f2-9f0953630ccf)

### Reproduction steps

```bash
1. Открыть тестовую страничку для отчётов https://hexlet.github.io/hexlet-correction/index.html
2. Выставить увеличенный масштаб (125%, например)
3. Выбрать любой текст и нажать Ctrl + Enter
```

### Expected result

Окно полностью отображается и адекватно реагирует на то, что масштаб страницы изменён

### Actual result

Окно отображается обрезанным и пользователь не видит кнопки управления

### Browsers

Microsoft Edge

### OS

Windows

**Comment by asenka0301** [comment]
Привет, возьму в работу)

**Comment by fey** [comment]
@asenka0301 Анастасия, добрый день.
Как у вас успехи? Я Предлагаю задачку дать другим ребятам, если подвижек нет =)

**Comment by Mari-Krukovskaya** [comment]
Возьму в работу )

**Comment by asenka0301** [comment]
Привет) я в процессе, до конца следущей неделе доделаю, если не успею, то отдам задачу.

**Comment by asenka0301** [comment]
Привет) проблему решила, пулл реквест создала
