### ISSUE TITLE
Bug: Кнопка "О проекте" в футере ведёт на информацию о другом сервисе

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#214]
### Summary

![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/e0e80238-06ea-4720-be6a-6a9223576534)

### Reproduction steps

```bash
1. Открыть лендинг
2. Прокрутить до футера
3. Нажать на "О проекте"
```

### Expected result

Страничка "О проекте" Hexlet-Correction

### Actual result

Страничка "О проекте" Hexlet-SICP

**Comment by TonyMudRec** [comment]
Готово к мерджу
https://github.com/Hexlet/hexlet-correction/compare/main...TonyMudRec:hexlet-correction:tonyk?expand=1
