### ISSUE TITLE
Bug: Создание одним авторизованным пользователем несколько сниппетов с пустым именем в одном языке программирования

### ISSUE THREAD

**Issue by kairina2020** [Hexlet/hexlet-correction#225]
### Summary

Авторизованный пользователь создавая новый сниппет на JS может сохранить его под пустым именем. Таким образом можно создать несколько сниппетов без "возражения" сервиса. 

В Allure OPEN Defect #397 Есть возможность создать сниппет с пустым именем

### Reproduction steps

```bash
Test-case #2377 Создания сниппета с пустым именем
Precondition
Пользователь авторизован и открыто окно со сниппетами

Scenario
1 На кнопке "Новый сниппет" нажать на иконку языка программирования
2 В открывшемся окне сниппета в поле имени нажать на иконку "карандаш"
3 Удалить все символы имени
4 Enter
5 Кликнуть по "Мои сниппеты " в верхнем меню
```

### Expected result

Невозможно создать сниппет с пустым именем

### Actual result

Сниппеты с пустым именем можно создать.  Даже несколько.
![Pustoe](https://github.com/Hexlet/hexlet-correction/assets/110185387/86403d0f-ca03-4560-9ff4-a8e21f8f12cd)
![Pustoe_1](https://github.com/Hexlet/hexlet-correction/assets/110185387/e0edd676-62c3-4ec8-877b-4b52bd1dd1a2)
![Pustoe_2](https://github.com/Hexlet/hexlet-correction/assets/110185387/60a31c3d-cb24-4772-9ed5-22b28007613f)

### Browsers

Chrome

### OS

Windows

**Comment by kairina2020** [comment]
@fey , на мой взгляд не серьезный, работе сервиса не препятствует, но неудобно при поиске, если много сниппетов

**Comment by fey** [comment]
@kairina2020 кажется это ищщус должен быть в runit? верно?

**Comment by kairina2020** [comment]
@fey , Николай, сегодня все переделаю. 
Мне для себя можете сказать, это является багом? или это предусмотренная возможность по документации)
