### ISSUE TITLE
Добавить проверку хоста с которого выполняются запросы с виджета

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#236]
### Problem description

Сейчас у нас нет проверки на то, откуда идет запрос с виджета. можно отправлять хоть через апишку, хотя это не очень безопасно.

### Proposed solution

Добавить возможность настраивать воркспейс - добавлять домены, откуда можно отправлять запросы с виджета. Это может быть несколько сайтов/доменов для одного воркспейса.
Это позволит защитить замусоривание чужого воркспейса.

**Comment by bazilval** [comment]
Возьму

**Comment by bazilval** [comment]
> можно отправлять хоть через апишку

Вроде как пробую, и через консоль браузера делать запросы (просто скопировал из нашего index.js) и они не проходят. Как раз-таки CORS их и останавливает из-за того, что просто делая сложный POST-запрос без preflight OPTION-запроса ничего не работает.

Но если отлавливать запросы при работе виджета, то он делает этот preflight запрос (хотя по идее тоже вызывается тем же JS) и CORS пропускает

Пока не понял при каких условиях javascript решает, что он должен сделать этот preflight запрос. По идее его на этого должно толкнуть сочетание Post и json-контента. Возможно ли, что из-за того, что при обычной работе запрос делается именно браузером, он это всё учитывает?

**Comment by bazilval** [comment]
@fey привет, можем ли немного обсудить эту фичу?

Мы можем добавить CORS проверку на сервере, однако это не поможет нам с запросами через апишку, так как заголовок Origin можно вручную подделать любой желаемый. При этом токен любой желающий может достать из скрипта интеграции на странице.
До какой степени мы будем пытаться защититься?

**Comment by fey** [comment]
@bazilval 
Ну мне кажется сейчас на 100% защититься не сможем. Например у Sentry тот же токен можно вытащить. Пока что просто настраиваем CORS

**Comment by bazilval** [comment]
@fey просто ты упомянул в ишью про апишку и я пока не вижу как можно защититься от таких запросов, только выдавать какие-то одноразовые токены на каждый запрос

по CORS сделаю, но это как-будто не особо страшно, сложно представить ситуацию, когда кто-то на страничку добавляет виджет с чужим URL и токеном, чтобы замусорить чужой воркспейс

**Comment by fey** [comment]
Нууу, как говорится это проблема будущих нас. Щас же и пользователей нет)

**Comment by fey** [comment]
Насчет апишки подумаем позднее.

**Comment by bazilval** [comment]
@fey closed
