### ISSUE TITLE
Сверстать лендинг для главной страницы

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#240]
### Problem description

Сейчас лендинг сверстан на коленке и выглядит некрасиво. Нет понимания, что это, какую боль (проблему) решает и кому пригодится. 

### Proposed solution

Сверстать новый лендинг. 2-3 блока, которые описывают сервис и призывают зарегистрироваться на платформе.
Для верстки нужно использовать стандартный Bootstrap (его возможностей должно хватить). Можно посмотреть другие сервисы Хекслета и лендинги, чтобы как должно выглядеть.
Обязательно - на первом экране должна быть кнопка, призывающая к регистрации на сервисе.
Сам сервис называется FixIt. Для старта можно сверстать общий скелет, который можно будет наполнить осмысленным текстом.

**Comment by KarnaDev** [comment]
@arthur810629 @fey Ребята, привет! Как у вас дела с лэндтнгом? Что-то продвигается?
Хотела присоединиться

**Comment by fey** [comment]
@KarnaDev ока ждем ответа от Артура, можно поверстать лендинг для hexlet-friends https://github.com/Hexlet/hexlet-friends/issues/388

**Comment by fey** [comment]
@KarnaDev задачка свободна. Если вы или кто-то еще хочет взять - можете взять в работу.

**Comment by VictoryPashkova** [comment]
Возьму задачу

**Comment by VictoryPashkova** [comment]
Взяла задачу

**Comment by fey** [comment]
Теерь осталось этот леднинг нарезать и прикрутить на главную

**Comment by fey** [comment]
@shamshaev can you do it? we have template https://github.com/Hexlet/hexlet-correction/blob/main/src/main/resources/templates/landing.html

**Comment by shamshaev** [comment]
Yes, I think I can do it. As I understand it's just some work with templates, not the real frontend.

It's a pity that there is no real backend issue left, but it is what it is. At least Hexlet-Corrector will look normal, because now it looks like "бедный родственник" among other Hexlet open source projects.

**Comment by shamshaev** [comment]
@fey I understand the situation, no problem, I will do it.

Regarding #199 - I checked it already and it's very unclear now. The main part is done - Gradle. What's next thing - unclear. It seems like - do something, we don't care. Probably somebody should put some top 3 tasks there and people will take one by one. This is just my opinion.

**Comment by shamshaev** [comment]
@fey Is widget in English available somewhere? I'd like to make landing in English also, but seems like widget exists only in Russian. I thought maybe it depends from system language of browser or operating system, changed everywhere to English, but widget anyway in Russian.

![Screenshot from 2024-09-25 14-02-46](https://github.com/user-attachments/assets/e823e506-3955-4d84-9b98-c8696ae30e46)

**Comment by fey** [comment]
@shamshaev no currently we dont have i18n for widget. 
You can create en/ru landing and add todo for screenshot that depends on locale.
And someone will upgrade widget for multiple locales https://github.com/Hexlet/hexlet-correction/blob/main/src/widget/index.js

**Comment by shamshaev** [comment]
@fey I deployed updated app. Here is the link: https://hexlet-correction-3.onrender.com/
Please, check and give your feedback - is it OK? Maybe I should add something else or remove.

Here is the list of changes:

1. Navbar is updated:
 - added button "My Workspaces"
 - improved logic: when you press "FixIT", you get to the main paig, not the workspaces (like before). For workspaces there is a separate link now. Also pressing "username" when you are logged in, leads to account, not the main page (like before). I wanted to fix it anyway, but somebody opened an ISSUE #305 already.
 
2. Home page is updated:
 - added prepared code from landing.html
 - added English (except widget)
 - buttons "Sign Up" and "Login" only visible if you are not logged in 
 
3. Footer is updated:
 - added it on all pages. It's ISSUE #153
 - adapted style a little bit
 - updated list and links to actual other open source projects
 - added English
 
4. Head is updated:
 - changed title
 - added favicon (actually now it's not in the head, later I changed solution to the Spring Boot specific one)
 - added meta information about project
 
5. Page "about project" is updated:
 - made same style as other pages
 - added English
