### ISSUE TITLE
Bug: при выделении только одного символа в виджете появляется дублирование

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#245]
### Summary

Баг не постоянен и я не смог выяснить почему иногда появляется.
Выглядит это вот так:
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/2f448e33-2232-4c96-b60c-45e0762daa1e)
Появляется только при выделении одного символа и не каждый раз.

### Reproduction steps

```bash
1. Открыть https://hexlet.github.io/hexlet-correction/index.html
2. Выбрать любой один символ
3. Нажать Ctrl + Enter
4. Проверить появились ли лишние символы
5. Если нет, повторить пункты 3 и 4 несколько раз
```

### Expected result

Вокруг жирного подчёркнутого символа не должно быть его дублирований

### Actual result

Периодически символ дублируется

### Browsers

Microsoft Edge

**Comment by bazilval** [comment]
Получилось словить эту штуку на полном слове
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/45f0f659-9570-4183-9225-253916a8ede6)

**Comment by fey** [comment]
пока не удалось воспроизвести

**Comment by bazilval** [comment]
@fey попробую в других браузерах ещё

**Comment by bazilval** [comment]
@fey попробовал в режиме инкогнито и на другом устройстве, баг повторяется, но так же нерегулярно. Выглядит будто случайно, но удалось заметить, что если перед этим в холостую нажать комбинацию Ctrl + Enter, то баг появляется с большей вероятностью

Демо:
![Анимация](https://github.com/Hexlet/hexlet-correction/assets/29205112/ecfea009-b83c-43d1-b665-b1a50967f36c)

**Comment by GrandVandal** [comment]
Все привет, попытался воспроизвести и обнаружил закономерность. Если начало у выделения стоит левее его конца то бага нет, а если начало выделения стоит правее его конца то происходит дублирование.

Также виджет некорректно работает при выделении на границе двух разных элементов страницы.

**Comment by GrandVandal** [comment]
Забыл вас тэгнуть @fey @bazilval

**Comment by bazilval** [comment]
@GrandVandal Отличная наблюдательность! Видимо что-то с алгоритмом расчёта фрагментов. Скорее всего он для "фрагмента до" берёт от начала контекста до начала выделения, а для "фрагмента после" берёт от конца выделения до конца контекста. А конкретно в этих случаях у нас начало выделение и конец выделения перепутаны местами
