### ISSUE TITLE
Bug: возможность сделать репорт на содержимое виджета

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#248]
### Summary

После открытия виджета для отправки опечатки возможно выделить текст в самом виджете и снова нажать Ctrl+Enter, что приведёт к открытию виджета для опечатки с этим текстом. Вряд ли это желаемое поведение. Возможно стоит проверять открыто ли окно, перед реагированием на ивент нажатия комбинации клавиш.

![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/212accf2-fdd4-4ed7-8e64-7d20573566e4)

### Reproduction steps

```bash
1. Открыть https://hexlet.github.io/hexlet-correction/index.html
2. Выбрать любой текст и нажать Ctrl + Enter
3. В открывшемся виджете снова выбрать любой текст и нажать Ctrl + Enter
```

### Expected result

Ничего не должно происходить

### Actual result

Переоткрылось окно с опечаткой

**Comment by GrandVandal** [comment]
Возьмусь за проблему

**Comment by GrandVandal** [comment]
Отправил PR
