### ISSUE TITLE
В тесты добавить проверку ответа по jsonschema через restassured

### ISSUE THREAD

**Issue by malikin** [Hexlet/hexlet-correction#25]
Надо добавить проверку ответа нашего апи через restassured и валидация по jsonschema. RestAssured уже прикручен, осталось описать схему сущностей и проверять их.

**Comment by MisterCool** [comment]
Можно взять?)

**Comment by malikin** [comment]
@MisterCool бери!

**Comment by malikin** [comment]
closed by https://github.com/Hexlet/hexlet-correction/pull/32
