### ISSUE TITLE
Bug: слиплись кнопки в блоке опечатки

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#251]
### Summary

Не очень эстетично, хочется между ними какого-то отступа
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/2bcfd0b3-ba69-4927-b82f-edbb4c8dcf2a)

### Reproduction steps

```bash
1. Открыть воркспейс
2. Открыть любую из опечаток
```

### Expected result

В блоке информации о воркспейсе хороший пример того, как надо: между кнопками есть отступ
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/436ca49e-076b-48d1-a462-dad23957fc40)

### Actual result

Кнопки склеились

**Comment by kitdim** [comment]
Возьму!
