### ISSUE TITLE
Bug: the name of the workspace on the integration page is missing

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#254]
### Summary

Integration page:
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/c1f4f012-c153-4b6e-b20b-b389baff603a)

Other pages:
![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/a7183c68-c855-41b3-aed5-973b2395b6cb)

### Reproduction steps

```bash
1. Open the integration page for any workspace.
```

### Expected result

The name of the workspace should be displayed on all tabs.

### Actual result

The name of the workspace on the integration page is missing.

**Comment by fey** [comment]
Ощущение, что не прописали шаблон от которого надо наследоваться :thinking:
