### ISSUE TITLE
Bug: лишние элементы на странице пользователей

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#255]
### Summary

Лишний label с надписью email, а также, по-видимому, случайно скопированная строка с датой последней опечатки. Очевидно, что на страничке добавления пользователей она лишняя

![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/8b1bdca7-d120-466c-bc72-3952c1d7bb2e)

### Reproduction steps

```bash
1. Открыть страничку пользователей у любого воркспейса
```

### Expected result

Отсутствие лишних элементов

### Actual result

Их присутствие

**Comment by kitdim** [comment]
Взял.

**Comment by bazilval** [comment]
@kitdim думаю сперва стоит дождаться апрува от @fey

Обычно он отмечает ишью одним из тегов, чтобы было видно, что задачу можно брать в задачу

**Comment by kitdim** [comment]
@bazilval оке

**Comment by fey** [comment]
@bazilval а у меня нет last typo. 
Насчет лейбла - скорее его надо подвинуть выше, над инпутом. Ведь мы вносим емейл юзера. Но в целом да, конкретно тут лишнее, можно убрать Если дата опечатки выводится, ее можно убрать. @kitdim попробуйте :) 
![image](https://github.com/Hexlet/hexlet-correction/assets/697178/d156b588-6a44-494c-bc4a-79bac96047d3)

**Comment by bazilval** [comment]
@fey странно, что у вас нет, кстати
этот блок в разметке шаблона точно есть
