### ISSUE TITLE
Bug: Workspace почему-то должен иметь уникальное имя

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#264]
### Summary

На данный момент workspace не может быть создан с одним и тем же именем, что кажется довольно странным, учитывая, что пользователь может захотеть назвать свою доску как угодно и не должен учитывать названия досок у всех остальных. Для уникальности есть id.

При чём попытка создания доски с тем же названием, никак не перехватывается

### Reproduction steps

```bash
1. Создать доску с любым названием
2. Создать ещё одну с тем же названием
3. Словить необработанное исключение
```

### Expected result

Доска создаётся без проблем

### Actual result

Выводится необработанная ошибка на сервере

**Comment by kitdim** [comment]
возьму

**Comment by bazilval** [comment]
пушни на репу, чтобы посмотреть что там у тебя

**Comment by bazilval** [comment]
@kitdim привет!
А что за constraintName такое у тебя? "uk_br8l0q43h1ygdohbp4htocj3h"

Я вот в самом первом changeSet [нашёл](https://github.com/Hexlet/hexlet-correction/blob/dcfd1c0f5e610a36c084a20fa83b9a5ce6dc032a/src/main/resources/db/changelog/changesets/2021/04/20211904104233167-create-workspace-table.xml#L35) такой констрейнт на уникальность имени доски

```
    <changeSet id="20211904104233167-3" author="system">
        <addUniqueConstraint columnNames="name" constraintName="UC_WORKSPACE_NAME" tableName="workspace" />
    </changeSet>
```

Может надо попробовать это имя подставить?

**Comment by kitdim** [comment]
@bazilval привет)
А его в бд в схеме нашел.
Да ты прав, там плюс добавил отключение workspace_name_key. 
После этого всё ок, ща изменение запулю

**Comment by kitdim** [comment]
@bazilval cпасибо!

**Comment by bazilval** [comment]
@kitdim а что за workspace_name_key?

**Comment by kitdim** [comment]
Похоже констрейнтов для name было два. Если отключить только UC_WORKSPACE_NAME, последуется провера на workspace_name_key, и появляется такая же ошибка как с UC_WORKSPACE_NAME
![image](https://github.com/Hexlet/hexlet-correction/assets/45449261/010c7210-24c8-4a5a-a3cf-bd93e38ca43a)

**Comment by bazilval** [comment]
@kitdim хм, а ты не нашёл в какой момент его добавляли и зачем?

**Comment by kitdim** [comment]
@bazilval добавили в этом [коммите](https://github.com/Hexlet/hexlet-correction/commit/10826816459001f65138139f49ea8043da16bc95)
сама миграция [вот](https://github.com/Hexlet/hexlet-correction/blob/main/src/main/resources/db/changelog/changesets/2022/11/2022-11-03-add-unique-constraint-to-name-workspace.xml)

**Comment by bazilval** [comment]
@kitdim странно как-то, да?
вроде в самом коммите добавляют уникальность URL
а в миграции добавляют дублирующую уникальность имени

**Comment by kitdim** [comment]
@bazilval ага. Возможно это сделано специально, чтобы в будующем поправили)

**Comment by kitdim** [comment]
@fey привет! Закрываем?
