### ISSUE TITLE
Bug: Нелокализованный текст на странице настроек

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-correction#266]
### Summary

![image](https://github.com/Hexlet/hexlet-correction/assets/29205112/5f8f2174-dfad-4990-a971-56f3cb6e9853)

Данный текст захардкожен в разметке, нужно импортировать из файла локализации

### Reproduction steps

```bash
Открыть страницу настроек
```

### Expected result

Весь текст на том языке, который выставлен

### Actual result

В настройках язык английский, а текст русскоязычный

**Comment by DimRux** [comment]
Возьму в работу.
