### ISSUE TITLE
Bug: Не работает кнопка "Hexlet Typo Reporter" на странице "О проекте"

### ISSUE THREAD

**Issue by 2laexe** [Hexlet/hexlet-correction#272]
### Summary

При переходе на страницу "О проекте" (https://fixit.hexlet.io/about) кнопка "Hexlet Typo Reporter" становится неактивной.

### Reproduction steps

```bash
1. Перейти на страницу https://fixit.hexlet.io/
2. Нажать "О проекте"
3. Нажать "Hexlet Typo Reporter"
```

### Expected result

Произошел переход на страницу https://fixit.hexlet.io/workspaces

### Actual result

Кнопка не активна
![1](https://github.com/Hexlet/hexlet-correction/assets/100873772/ea375092-ba91-4a81-9a0c-e8454926509a)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
Ага, там какой-то косяк с шаблонами

**Comment by kitdim** [comment]
возьму!

**Comment by bazilval** [comment]
@kitdim можете закрыть ишью

**Comment by kitdim** [comment]
@bazilval привет, так не я создалеть
