### ISSUE TITLE
Bug: Incorrect link and name of the 'Knowledge Base' button on the home page

### ISSUE THREAD

**Issue by 2laexe** [Hexlet/hexlet-correction#274]
### Summary

Ссылка на кнопке 'База знаний' "https://ru.hexlet.io/knowledge" на главной странице приводит к редиректу на "https://ru.hexlet.io/webinars". на странице https://ru.hexlet.io/ кнопка с URL "https://ru.hexlet.io/webinars" называетcя "Бесплатно"
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/75472ed1-80c1-4828-920e-277c1eff13ec)
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/6d8a903b-5216-4dc6-9027-a158ca8bcb99)
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/318a3182-fe22-4e3e-9d48-c8285ca2de72)
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/eb6af9a2-33f8-4232-9f5e-1dfe73c4b394)

### Reproduction steps

```bash
1. Перейти на главную страницу сайта https://fixit.hexlet.io/.
2. Кликнуть на ссылку "База знаний".
3. Происходит редирект на страницу вебинаров.
```

### Expected result

Кнопка должна называться "Бесплатно" и вести напрямую на страницу вебинаров `https://ru.hexlet.io/webinars`.

### Actual result

Кнопка называется 'База знаний' и ведет на `https://ru.hexlet.io/knowledge`, после чего происходит редирект на страницу вебинаров `https://ru.hexlet.io/webinars`.

### Browsers

Chrome

### OS

Windows

**Comment by Grad566** [comment]
Беру в работу

**Comment by Grad566** [comment]
На https://ru.hexlet.io/ кнопка называется 'учиться бесплатно'.
Может быть, здесь тоже лучше переименовать в 'учиться бесплатно', чем просто в 'бесплатно'?
Просто из названия 'бесплатно' не особо понятно о чем речь.

**Comment by 2laexe** [comment]
> На https://ru.hexlet.io/ называется кнопка «учиться бесплатно». Может быть, здесь тоже лучше переименовать в «учиться бесплатно», чем просто в «бесплатно»? Просто название «бесплатно» не совсем понятно, чем речь.

Они обновили сайт на днях:) так что да, теперь «учиться бесплатно»
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/3f1b8d3a-1913-402b-a696-d923d8529440)

**Comment by bazilval** [comment]
@fey Closed

**Comment by fey** [comment]
еще рано, на проде ссылка ведет на старое
