### ISSUE TITLE
Bug: Проблемы с адаптивностью

### ISSUE THREAD

**Issue by 2laexe** [Hexlet/hexlet-correction#275]
### Summary

На странице просмотра информации "Пространства" наблюдаются проблемы с адаптивностью при просмотре на мобильных устройствах. Элементы интерфейса перекрывают друг друга, что делает страницу трудной для использования.

### Reproduction steps

```bash
1.Откройть страницу "https://fixit.hexlet.io/workspaces" на мобильном устройстве или в режиме эмуляции мобильного устройства в браузере.
2.Нажать ссылку "Информация"
```

### Expected result

Элементы интерфейса должны корректно отображаться на экранах мобильных устройств. Все элементы должны быть видимыми и не должны перекрывать друг друга.

### Actual result

Меню навигации перекрывает текст и другие элементы.
Кнопки и таблица не выровнены должным образом.
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/0e7d43db-3637-403b-baed-763100d92279)
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/4d1bfc26-d7a1-479c-bd0d-78eb45e704eb)
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/2b13322a-81c3-40a4-847b-8cfc96d8e88b)
![image](https://github.com/Hexlet/hexlet-correction/assets/100873772/f7de6395-5462-46ca-9de2-9fac13f426cc)

### Browsers

Chrome

### OS

Windows

**Comment by bazilval** [comment]
Дублирует эту [issue](https://github.com/Hexlet/hexlet-correction/issues/261)
