### ISSUE TITLE
Translate issues into English 

### ISSUE THREAD

**Issue by HelenOne** [Hexlet/hexlet-correction#282]
### Problem description

It has been decided that all open-source projects will be translated into English in order to make them more accessible to a global audience.

### Proposed solution

The task is to create a new English issue for each existing issue. You need to translate the title and the description into English, and provide the context of the confirmation in the comments. Also, you should refer to the original Russian task. Old issues will be archived.

You can use the [Yandex Translate editor](https://translate.yandex.ru/editor).

**Comment by niyatanya** [comment]
Hi! I can take translation of any 5-10 issues. I will be happy to cooperate with someone on this task!

**Comment by dtarakanova** [comment]
Hi! Can join for translation of 5-10 issues)

**Comment by fey** [comment]
@dtarakanova @niyatanya I invited you to the repository. Check the notifications. You will be able to edit (translate) task texts (you can use DeepL)

**Comment by Maxonquall** [comment]
Hello, can I join in the translation? :)

**Comment by niyatanya** [comment]
> @fey Thanks! I got the access to the repository, however I do not see the button to edit the issue. Please advise if I am looking in a wrong place) 
![image](https://github.com/user-attachments/assets/f825febb-a5db-4bac-b98a-1cc369dd8b61)

**Comment by fey** [comment]
@Maxonquall yes, i can give you access to another repo

**Comment by fey** [comment]
@Maxonquall pls check github's notifications

**Comment by fey** [comment]
@Maxonquall Yeah, I figured since you studied Java, you'd be more interested in this repository than others =)

**Comment by niyatanya** [comment]
@fey It worked! I can edit issues now. 
Today translated two issues: [#276](https://github.com/Hexlet/hexlet-correction/issues/276) and [#267](https://github.com/Hexlet/hexlet-correction/issues/267). Kindly check them, if Ok I`ll procees with some more.

Just in case: I will take around 5 more issues, so translation of other issues is still vacant! ⚒️

**Comment by Maxonquall** [comment]
@fey I translated the problems #261 and #177  . Please look at them too, did I understand the problem correctly?)

**Comment by fey** [comment]
@Maxonquall yes, looks good. I usually use deepl for translations, it's almost good

**Comment by fey** [comment]
@Maxonquall @niyatanya Hello, how are things going?

**Comment by niyatanya** [comment]
Will finish 5 more by the end of the week.

**Comment by Maxonquall** [comment]
Hi, I'll be doing some translations by the end of the week too.

**Comment by niyatanya** [comment]
Just finished 5 more. Eight issues left untranslated in Hexlet-correction. My job is done here! ⚒️ @Maxonquall @dtarakanova catch up! 

P.S. If any help here needed, please feel free to tag me.

**Comment by Maxonquall** [comment]
Just finished translating the remaining issues. @dtarakanova you can make improvements to the translation if you want :)

**Comment by dtarakanova** [comment]
Thanks for the info, will focus on other threads then👌
