### ISSUE TITLE
Make first name, last name be optional (empty)

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#286]
### Problem description

There are too many fields that are required to register.
![image](https://github.com/user-attachments/assets/55065a62-f63f-44d8-a667-0f52be453cf8)

### Proposed solution

Make First Name, Last Name fields optional, remove them from the registration field, allow them to be empty. We have enough data to identify the user - by login, by mail.

**Comment by Grad566** [comment]
I'll take this issue. 
I understood correctly that it is necessary to remove these fields from the registration. Or they can just remain empty when registering a new user?

**Comment by uchitsa** [comment]
Hi, already do it task. Please see PR #299

**Comment by uchitsa** [comment]
https://github.com/Hexlet/hexlet-correction/pull/299#issuecomment-2314770811
