### ISSUE TITLE
Bug: User is registered with an incorrectly confirmed Password

### ISSUE THREAD

**Issue by Alena007S** [Hexlet/hexlet-correction#291]
### Summary

User is registered with an incorrectly confirmed Password

### Reproduction steps

```bash
1. Enter a valid Username
2. Enter a valid Email
3. Enter a valid First Name
4. Enter a valid Last Name
5. Enter Password "147258369"
6. Validate Password "123456789"
7. Click Create Account
```

### Expected result

User is not registered. The message appears: "Password and Confirm Password do not match."

### Actual result

User is registered.

### Browsers

Chrome

### OS

Windows

**Comment by SibirBear** [comment]
Доброго времени суток!
Задача актульна? Хотел бы взять в работу.

**Comment by Alena007S** [comment]
@SibirBear  Yes, error is still valid
