### ISSUE TITLE
Bug: Registration with an invalid email is possible, part of the domain name is missing

### ISSUE THREAD

**Issue by Alena007S** [Hexlet/hexlet-correction#292]
### Summary

Registration with an invalid Email is possible, part of the domain name is missing. Email like: 123@.com

### Reproduction steps

```bash
1. Enter a valid Username
2. Enter invalid Email like "user_2023@.tu"
3. Enter valid First Name
4. Enter a valid Last Name
5. Enter Password
6. Confirm Password
7. Press button "Create Account"
```

### Expected result

Registration was not successful.
The message "The email is not valid" appears 
The field is highlighted in red

### Actual result

Registration was not successful.
But the error does not appear, the field is not highlighted in red.
![456](https://github.com/user-attachments/assets/2997cfb8-a853-43a6-9f53-554dda570c5d)

### Browsers

Chrome

### OS

Windows

**Comment by SibirBear** [comment]
Now there is such an alert when performing the described steps. Is this incorrect?

--
Сейчас такое оповещение при выполнение описанных шагов. Это не корректно?

OS: Windows 10   Browser: Chrome    (https://fixit.hexlet.io/)
![image](https://github.com/user-attachments/assets/fae94df5-da89-479d-9eea-36302cc4c8f8)

OS: Ubuntu   Browser: Firefox   (lastcode in project on local machine)
![image](https://github.com/user-attachments/assets/ef3eb945-6186-46ce-917e-9361ea10f6f5)

**Comment by Alena007S** [comment]
@SibirBear у меня Версия Windows 10, Chrome127.0.6533.100 по прежнему нету никакого оповещения

**Comment by funnyDevGirl** [comment]
OS Ubuntu 22.04, Chrome 127.0.6533.88 (Официальная сборка), (64 бит)
![Снимок экрана от 2024-08-15 08-52-03](https://github.com/user-attachments/assets/2f9ab3dc-1226-41f4-83db-77c3ee6d03e8)

**Comment by funnyDevGirl** [comment]
OS Ubuntu 22.04,  Firefox 129.0 (64-разрядный)
![Uploading Снимок экрана от 2024-08-15 08-58-04.png…]()
