### ISSUE TITLE
Bug: Not all text changes to Russian when changing the language in Workspace -> Users

### ISSUE THREAD

**Issue by Alena007S** [Hexlet/hexlet-correction#293]
### Summary

In the Workspace section (in the Users section), when change the language to Russian, part of the text remains untranslated. 

### Reproduction steps

```bash
1. Log in
2. Press the Users button
3. click the language button
4. Select Russian language
```

### Expected result

All text on the page must be displayed in Russian.

### Actual result

Part of the text is displayed in English.
![12](https://github.com/user-attachments/assets/afecff95-1d07-45b6-8121-857ab262b525)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
"email" column header can be en english, it is ok. Placeholder in input can be translated

**Comment by Ymirotvorenie** [comment]
I'll take it
