### ISSUE TITLE
feature request: Display user name with email 

### ISSUE THREAD

**Issue by Luorika** [Hexlet/hexlet-correction#304]
### Summary

When registering a user must specify username. But when authorizing on the site, the top panel displays email instead of username. 

### Reproduction steps

```bash
1. log in
2. View the top panel.
```

### Expected result

The username is displayed.

### Actual result

Email is displayed.
![screen03](https://github.com/user-attachments/assets/3226e3e2-c61a-42cc-a093-7cfe91082130)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by fey** [comment]
We can display User's name AND email 
Screens from codebasics and hexlet-cv for example:
![image](https://github.com/user-attachments/assets/3610a2d6-2fc2-4567-a293-a7e3df6aad01)
![image](https://github.com/user-attachments/assets/bd52d942-9e01-48a8-9776-fc617b79dece)

**Comment by Nika-code** [comment]
Hi, could I start working on this? could you assign it to me?

**Comment by fey** [comment]
@Nika-code fork repository, create branch and go code =)
I assigned to you task

**Comment by Nika-code** [comment]
Hi, @fey I've created pull request for this task, could you take a look at it?
