### ISSUE TITLE
Remove link from user email in nav bar

### ISSUE THREAD

**Issue by Luorika** [Hexlet/hexlet-correction#305]
### Summary

Clicking on the username in the top bar takes you to the home page, and clicking on the site name takes you to the list of user spaces. 

### Reproduction steps

```bash
1. log in
2. Click on the user name in the top panel.
3. Click on the site name in the top panel.
```

### Expected result

Clicking on the username loads the user profile or the list of spaces. 
Clicking on the site name loads the home page. 

### Actual result

Clicking on the site name loads the list of spaces. 
Clicking on the user  name loads the home page. 
![screen04](https://github.com/user-attachments/assets/57006674-8b7f-49c3-bc98-7364a7a36aea)
![screen05](https://github.com/user-attachments/assets/040c41f7-5325-4cb7-8b01-08799121af4b)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
We can remove link from email in nav bar

**Comment by Nika-code** [comment]
Hi @Luorika , @fey I'd like to work on this issue. Can you assign it to me?

**Comment by fey** [comment]
Yes, do it

**Comment by Nika-code** [comment]
I've made changes, created new branch and wanted to push changes and create pull request but I get error code 403 (forbidden) when trying to do so.

**Comment by fey** [comment]
@Nika-code you should fork repository and push to you repo =) 
https://ru.hexlet.io/blog/posts/Open-Source-github
