### ISSUE TITLE
Bug: Add link to 'Workspaces' in header

### ISSUE THREAD

**Issue by Luorika** [Hexlet/hexlet-correction#307]
### Summary

It is difficult for the user to understand how to go to the list of spaces from another section of the sit

### Reproduction steps

```bash
1. log in
2. Go to Account Information
3. Find the button to go to Created spaces
```

### Expected result

The button to go to Created Spaces is easy to find.

### Actual result

The button to go to Created Spaces is unclear where it is located.
![screen08](https://github.com/user-attachments/assets/6f81bf37-1923-4121-a941-8a27d5b7b173)

### Browsers

Firefox

### OS

Windows

**Comment by fey** [comment]
Yea, we need add `Workspaces` into header nav

**Comment by Nika-code** [comment]
Hi, could I start working on this? could you assign it to me?

**Comment by fey** [comment]
@Nika-code do it =)

**Comment by CicadaN** [comment]
@fey actual ?

**Comment by Nika-code** [comment]
> @fey actual ?

@CicadaN I don't know if it's still actual, but if it is I was assigned to the issue, but I don't have the time to work on it now, so if it still needs to be done, I unassigned myself so you can do it

**Comment by fey** [comment]
Yes, still actual

**Comment by SplitCode** [comment]
@fey @CicadaN is there work going on here or can I take this task?

**Comment by fey** [comment]
@SplitCode yes, is acutal

**Comment by SplitCode** [comment]
I've created a PR, please take a look - https://github.com/Hexlet/hexlet-correction/pull/316
