### ISSUE TITLE
Fixtures

### ISSUE THREAD

**Issue by malikin** [Hexlet/hexlet-correction#41]
Добавить в тесты фикстуры, использовать эту библиотеку - https://github.com/database-rider/database-rider

 Defenition of done - подключена библиотека и в текущие тесты добавлены фикстуры, к примеру - есть тест с получением пользователя, убрать создание через фабрики а добавить Dataset c готовым пользователем и при тесте доствать его

В тестах с изменением сущности, сделать dataset изначальный и проверочный.

Пример есть тут - https://github.com/database-rider/database-rider/blob/master/rider-examples/spring-boot-dbunit-sample/src/test/java/com/github/database/rider/springboot/SpringBootDBUnitTest.java 

Как подключить к Spring есть в README библиотеки

**Comment by MisterCool** [comment]
готов взять на себя

**Comment by malikin** [comment]
@MisterCool Бери

**Comment by malikin** [comment]
closed by https://github.com/Hexlet/hexlet-correction/pull/49
