### ISSUE TITLE
Добавить code coverage

### ISSUE THREAD

**Issue by malikin** [Hexlet/hexlet-correction#5]
Добавить code coverage с выгрузгой в какой-нибудь сервис - https://codeclimate.com/ к примеру, настроить сборку проекта с проверкой порога покрытия, можно установить пока 80% там дальше решим если что.

**Comment by samokisha** [comment]
Нужно ли падать при coverage  меньше 80%?

**Comment by malikin** [comment]
@samokisha Конечно, в этом и идея, можно примерно как тут сделать - https://stackoverflow.com/a/41892357

**Comment by samokisha** [comment]
С помощью JaCoCo делаю. Интеграция будет с https://codecov.io/
Нужно зарегистрироваться там через hexlet.
И в Travis CI добавить переменную окружения `CODECOV_TOKEN="<UUID>"`.
UUID будет [тут](https://codecov.io/gh/Hexlet/hexlet-correction/settings)

**Comment by malikin** [comment]
@samokisha Сегодня уточнил  @mokevnin что покрытие на codeclimate будет отправляться

**Comment by malikin** [comment]
https://codeclimate.com/github/Hexlet/hexlet-correction

**Comment by samokisha** [comment]
Готово #12

**Comment by samokisha** [comment]
@mokevnin необходимо изменить идентификаторы в `README.md`  для бейджей.
```
[![Maintainability](https://api.codeclimate.com/v1/badges/<ID>/maintainability)](https://codeclimate.com/github/Hexlet/hexlet-correction/maintainability)
[![Test Coverage](https://api.codeclimate.com/v1/badges/<ID>/test_coverage)](https://codeclimate.com/github/Hexlet/hexlet-correction/test_coverage)
```

**Comment by samokisha** [comment]
Также необходимо добавить в Travis CI переменную окружения `CC_TEST_REPORTER_ID`
ID  здесь: https://codeclimate.com/github/Hexlet/hexlet-correction > _**Repo Settings**_ > _T**est coverage**_
