### ISSUE TITLE
Добавить скрипт подключения на сайт

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#78]
Добавить скрипт-интеграцию, который будет работать с бекендом и отправлять данные на сервис

>к сайту соот-но хотелось бы прикреплять не просто как скачивание какого-то файла, а по взрослому, через скрипт инициализации, который сам все сделат
>как в метриках всяких и прочем
чтобы была возможность изменения скрипта
сначала ты делаешь какой-то скрипт, который подлкючается к апи что-ли, а уже в этом апи скрипте происходит подключение и работа с DOMом

**Comment by DemX86** [comment]
1. Правильно ли я понимаю первый вариант реализации скрипта (который не «по-взрослому»):
− создаётся отдельный js-файлик, где прописана вся логика работы:
−− активация по нажатию Ctrl+Enter
−− появление свёрстанного модального окна с формой
−− отправка данных POST-запросом на бекенд
− этот файл скрипта потом вставляется в шаблон сайта в тег `<script>`

2. Тогда «взрослый» вариант должен выглядеть следующий образом:
− мы также добавляем в шаблон сайта в тег `<script>` какой-то js-код
− этот код отдельным запросом постучится куда-то на отдельный бекенд
− этот отдельный бекенд может принимать с передаваемым с запросом дополнительные параметры, позволяющие как-то модифицировать (подставлять нужные url или еще что-то) по сути то же содержимое описанного в предыдущем варианте файлика js
− бекенд выдаёт в ответ на запрос настроенный скрипт
− дальше скрипт работает так же, как было описано выше

Всё верно?

**Comment by kacetal** [comment]
@DemX86 Да вообщем то верно, только первый вариант можно упростить и делать через iframe.

**Comment by acidmaksim** [comment]
Example for widget(https://sicp.hexlet.io/ru) : 
<img width="518" alt="image" src="https://user-images.githubusercontent.com/77053797/188828964-b100923b-9a15-4e0c-a4bc-d1522904006b.png">

**Comment by antonkrupin** [comment]
возьму задачу в работу. попробую реализовать первый вариант, описанный выше.

**Comment by antonkrupin** [comment]
Добрый день! скрип сделал, данные из формы уходят, попадают в раздел typos созданного workspace. Но вопрос - как динамически получить workspacename и токен авторизации для отправки пост запроса? Сейчас я скопировал эти данные из созданного workspace и делал тестовые запросы.

**Comment by fey** [comment]
@antonkrupin тк сейчас фронтент формируется из шаблонов на сайте, можете создать issue, чтобы на странице настроек воркспейса выводили шаблонный код для вставки, в котором должен быть токен, id и так далее. 
Дальше юзер копирует этот код и вставляет себе на сайт.

**Comment by antonkrupin** [comment]
> @antonkrupin тк сейчас фронтент формируется из шаблонов на сайте, можете создать issue, чтобы на странице настроек воркспейса выводили шаблонный код для вставки, в котором должен быть токен, id и так далее. Дальше юзер копирует этот код и вставляет себе на сайт.

а потом мой скрипт со страницы парсит эти данные и подставляет при отправке формы?

**Comment by fey** [comment]
не очень понял.

**Comment by antonkrupin** [comment]
пользователь добавит шаблонный код, например в body data-атрибутами, а мой скрипт будет их оттуда получать, при отправке формы.

**Comment by fey** [comment]
в админке юзер видит код для сниппета, в нем прописан токен, нужные айдишики. Юзер копирует код, вставляет себе в страницу и может пользоваться отправкой опечаток.

**Comment by ssssank** [comment]
@fey кажется, этот ишью уже можно закрыть

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-correction/pull/158
https://github.com/Hexlet/hexlet-correction/pull/164
