### ISSUE TITLE
Перевести проект c Maven на Gradle

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#79]

**Comment by zxvfc** [comment]
Закинул [ПР с миграцией на градл](https://github.com/Hexlet/hexlet-correction/pull/83)

**Comment by kacetal** [comment]
Merged

**Comment by fey** [comment]
@kacetal получается, все еще актуально?

**Comment by kacetal** [comment]
Я бы оставил на мавен чтобы не решать проблемы билд системы. Но если кто и сделает пр то будем тестировать тщательно что все у всех работает, а не только во время ci.

**Comment by fey** [comment]
Ок, я ишшус тогда открою

**Comment by kacetal** [comment]
Я сделаю

**Comment by fey** [comment]
Актуально.

**Comment by fey** [comment]
@Malcom1986 получается все? Мы на градле?

**Comment by Malcom1986** [comment]
Ага
