### ISSUE TITLE
Автогенерация swagger (springfox)

### ISSUE THREAD

**Issue by malikin** [Hexlet/hexlet-correction#8]
Надо для облегчения дальнейшей разработки фронта и работы с api настроить автогенерацию доки в формате swagger, https://github.com/springfox/springfox

**Comment by malikin** [comment]
@samokisha  Надо добавить как попасть на страничку в README + я чтото не смог ее открыть, ошибка, проверь плиз и обнови README, после запуска проекта, через make, должна открываться, в этом же идея.

**Comment by samokisha** [comment]
@malikin Ок. С фронтом закончу, смерджу с мастером, потом займусь. Вот ссылка https://hexlet-correction.herokuapp.com/swagger-ui.html?urls.primaryName=full-api

**Comment by malikin** [comment]
Почему в доке только один контроллер?

**Comment by samokisha** [comment]
Справа вверху вибираешь `full-api` или конкретный контроллер

**Comment by malikin** [comment]
Если можно сделать по уполчанию full-api, сделай плиз, должно быть можно.

**Comment by samokisha** [comment]
Хорошо, займусь этим.

**Comment by samokisha** [comment]
Нет возможности кастомной сортировки или установки дефолтного (приоритетного) API.
Добавлю контроллер, который будет редиректить на `full-api`.
Или можно убрать все API кроме `full-api`.

**Comment by malikin** [comment]
Не надо редирект, оставь просто full, у нас там мало что будет :)
