### ISSUE TITLE
Добавить возможность приглашать в вокспейсы

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#82]
Сейчас воркспейсы доступны для гостей. Сделать возможность приглашать пользователей для совместной работы.
Например создатель воркспейса приглашает редактора

**Comment by fey** [comment]
хотя бы MVP версию сделать приглашения, потом остальное

**Comment by nekedio** [comment]
Постараюсь сделать.

**Comment by acidmaksim** [comment]
Задача свободна

**Comment by acidmaksim** [comment]
@nekedio как успехи, получается?

**Comment by nekedio** [comment]
Почти сделал. Исправления вношу.
