### ISSUE TITLE
Добавить checkstyle

### ISSUE THREAD

**Issue by zxvfc** [Hexlet/hexlet-correction#84]

**Comment by saymon-says** [comment]
@zxvfc Привет! Посмотри pull

**Comment by kacetal** [comment]
Нужно Sonar подключить.

**Comment by saymon-says** [comment]
> Нужно Sonar подключить.

Речь о SonarQube?

**Comment by kacetal** [comment]
Да

**Comment by nekedio** [comment]
Попробую разобраться.

**Comment by nekedio** [comment]
Из того, что я прочитал в разных местах:
1. У нас есть сервер SonarQube
2. У нас есть какой-то анализатор кода, который отправляет наш код для анализа на этот сервер
3. У нас есть плагин для ide, который подсвечивает ошибки, которые мы получили от сервера.
Если все проще и я что-то не так понял, ткните пожалуйста.

**Comment by acidmaksim** [comment]
@kacetal тыц

**Comment by nekedio** [comment]
@kacetal, можно вот так поступить:
Локально запускать sonarqube в контейнере (там нужно будет при первом запуске изменить пароль и получить токен)
Потом или плагином SonarLint или мавеном толкать туда результат анализа. Там все весьма наглядо.

Если все это автоматизировать мейком, все вполне будет работать. Другой вопрос сколько будет желания туда заглядывать.

**Comment by nekedio** [comment]
Таска в процессе. Пишу что б не потерялось.
Есть вот такой ресурс. https://www.sonarsource.com/products/sonarcloud/signup/
Туда @fey добавил наше "рабочее пространство".
Чтоб туда передать данные из проекта, юзаем токен SONAR_TOKEN

**Comment by fey** [comment]
А нам сонаркуб щас нужен? Чекстайла недостаточно? @Malcom1986

**Comment by kitdim** [comment]
@fey checkstyle я подключил, но там в приложении многовато отклонений от правил. с ними как?

**Comment by fey** [comment]
@kitdim создавайте пулл реквест, посмотрим на что жалуется

**Comment by kitdim** [comment]
@fey закрываем?

**Comment by fey** [comment]
Давайте.
