### ISSUE TITLE
Create Account entity

### ISSUE THREAD

**Issue by kacetal** [Hexlet/hexlet-correction#87]
Создать сущность `Account` которая будет представлять пользователя.

One Account has many Typo - bidirectional
One Workspace has many Account - bidirectional

Добавить миграцию для бд.
Добавить репозиторий и один метод поиска по email например.
Тесты.

**Comment by kacetal** [comment]
Fields principal for an Account:

```java
    private Long id;
    private String externalOpenId;
    private AuthProvider authProvider;
    private String email;
    private String username;
    private String password;
    private String firstName;
    private String lastName;
    private Workspace workspace;
    private List<Typo> typos;
```

**Comment by kacetal** [comment]
Скажите если кто берет эти issue

**Comment by saymon-says** [comment]
Я взял же

**Comment by kacetal** [comment]
Надо говорить тут, в issue

**Comment by saymon-says** [comment]
Так у меня вопросик. Сущность допустим я сделал. Тесты валятся теперь потому что соответственно все старые нужно переделывать(у нас же @NotNull account) и плюс новые писать. Это все в одном ишью? Все в один пуллреквест кидать?

p.s с тестами я буду сидеть очень долго, потому что такие вещи я вообще впервые вижу

**Comment by kacetal** [comment]
Да всё в одном pr, но можешь разделить на коммиты

**Comment by kacetal** [comment]
Смотри выкладывай комит с сущностью одной, я его начну проверять. Потом дальше в эту же ветку выкладывай коммит с репозиторием. Потом добавь коммит с тестами.

**Comment by kacetal** [comment]
Сущность сделай полностью, смотри как сделано Typo, она будет очень похожа по структуре.

**Comment by saymon-says** [comment]
> Сущность сделай полностью, смотри как сделано Typo, она будет очень похожа по структуре.

Да я смотрел на конечно на `pgenum typoStatus` , если сделать аналогично овверайд одного метода то осилю. Просто начал копать дальше в класс `typoStatus` и поплыл

**Comment by kacetal** [comment]
TypoStatus это просто обычный enum, делай енум и конвертируй его в енум постгреса

**Comment by kacetal** [comment]
Пока сделай сущность

**Comment by saymon-says** [comment]
#93

**Comment by saymon-says** [comment]
@kacetal у нас на пароль нет проверок никаких

**Comment by kacetal** [comment]
А какие должны быть по твоему мнению?

**Comment by saymon-says** [comment]
как минимум что он не пустой
``` // A-Za-z0-9_- / notBlank / length 2-20 / unique
    private String username;
    private String password;```
или это так так обозначил 2 поля,)

**Comment by kacetal** [comment]
Ну во первых он может быть пустым если мы будем oauth2 использовать. А во вторых, в случае сохранения пароля в базу данных мы будем хранить его хэш, так что проверка на символы не имеет смысла.

**Comment by kacetal** [comment]
Я бы для надежности хэшировал бы его сразу на фронтенде чтобы не пересылать пароль на бэкенд.

**Comment by saymon-says** [comment]
Согласовано

**Comment by kacetal** [comment]
Closed by #93
