### ISSUE TITLE
Не работает запуск приложения локально

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-correction#88]
Запускаю `make build-run`
```
BUILD SUCCESSFUL in 48s
9 actionable tasks: 8 executed, 1 up-to-date
docker-compose -f ./src/main/docker/postgresql.yml up -d --force-recreate
Recreating docker_typo-reporter-db-postgresql_1 ... done
java -jar -Dspring.profiles.active=dev ./build/libs/hexlet-typo-reporter-*.jar
no main manifest attribute, in ./build/libs/hexlet-typo-reporter-0.0.1-SNAPSHOT-plain.jar
make: *** [Makefile:4: run-dev] Ошибка 1
```

```java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

**Comment by zxvfc** [comment]
> no main manifest attribute, in...
Судя по всему дело в том, что мэйк билдит проект при помощи таски build и запускает, как _обычный_ jar-ник. Но build, по-моему не указывает какой класс должен быть main-классом.

Первое что приходит в голову, для сборки для запуска использовать таску install и запускать не через java -jar ..., а через sh файл который будет сгенерирован гадлом.
