### ISSUE TITLE
Создать страницу login / sign-in 

### ISSUE THREAD

**Issue by kacetal** [Hexlet/hexlet-correction#96]
Страница логина должна иметь два ввода username / password и иконку логина через GitHub

**Comment by kacetal** [comment]
Страница signin должна иметь два поля username / password.
username должен быть уникальным
password 8-30 символов, желательно хэшировать на фронте тем же енкодером что и на бэке ( BCrypt )

**Comment by saymon-says** [comment]
Схватил

**Comment by saymon-says** [comment]
так, что-то я делаю делаю, а судя по всему не то что нужно. login/sigin это что разные вещи у нас? Я предполагал что нужно login/sigup собственно вход либо регистрация.

**Comment by saymon-says** [comment]
"username должен быть уникальным" а откуда такое требование? У нас же не было изначально такого. email был уникальный

**Comment by saymon-says** [comment]
#99

**Comment by acidmaksim** [comment]
@kacetal привет, напиши плиз мне в тг @maximhexlet, есть пара вопросов по развитию проекта)

**Comment by IvanVyargizov** [comment]
Беру в работу

**Comment by saymon-says** [comment]
Да, правильно. У меня времени к сожалению нет, а идейный вдохновитель проекта тоже занят постоянно был

**Comment by acidmaksim** [comment]
@IvanVyargizov как у тебя успехи?

**Comment by IvanVyargizov** [comment]
@acidmaksim В процессе, время работать есть только по вечерам, в выходные плотно посижу, в пн дам обратную связь

**Comment by acidmaksim** [comment]
@IvanVyargizov Как дела с задачей?

**Comment by kacetal** [comment]
Хочу напмнить что login должен идти через стандартные механизмы Spring Security, а не через контроллер. Нужно будет создать имплементации сервиса который будет отдавать UserDetails

**Comment by IvanVyargizov** [comment]
@acidmaksim пусть задачу возьмет кто-нибудь другой

**Comment by Kvas1988** [comment]
Я возьму

**Comment by alexeiak** [comment]
> Я возьму
Мы тут с Иваном как раз сегодня тоже решили парно попрограммировать эту задачу. 
Написал тебе в слак.

**Comment by kacetal** [comment]
Исправил остаток и смерджил, если есть вопросы можете в слак писать.
